#!/usr/bin/env python3
"""Derive `docs/integrations/torq/processes.md` from the pipeline registry.

Implements the decision recorded as the question bank (issue #78):
operational docs are **generated at build, committed, and checked in CI**,
and where the source and the document disagree **the source is right by
definition**. There is no reconcile step where a human decides; the document
has no independent authority.

## What it extracts, and from where

Everything printed here is read from code that already declares it:

    uqf_stack.model.pipelines.PIPELINES   procname, script, kind, port
                                            offset, the table it owns, its
                                            subscribe/publish edges
    uqf_stack.stack.procs                 the vendored process.csv rows,
                                            so the vendored stack is counted
                                            rather than remembered
    uqf_stack.model.schemas               the table definitions, by name

Nothing is authored in this script. That is the point: the hand-written
`docs/integrations/torq/README.md` listed uqf's processes in prose and had already gone
stale - it omitted `tap1`, which has been in the registry since the tap
pipeline was added. Nobody noticed, because prose cannot fail.

## Why the edges are trustworthy

`subscribes`/`publishes` are declarations, and a declaration can lie. They
are checked against each pipeline's own q script by
`uqf_stack.model.pipelines.verify_pipeline_edges`, which runs in the test
suite - so the chain is *q script -> declaration -> document*, with a check
at each arrow. This script refuses to generate if that check fails, because
a diagram derived from a wrong declaration is worse than a stale one: it
looks authoritative.

`--check` regenerates in memory and diffs against the committed file,
exiting non-zero on any difference. That is the CI-facing mode.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

# parents[2], not parent.parent: this file sits one level deeper since
# scripts/ was foldered (#241). Getting it wrong does not raise - it
# resolves to scripts/ and the checker reports over an empty tree.
REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "python" / "uqf_stack" / "src"))

from uqf_stack.model import schemas  # noqa: E402
from uqf_stack.model.pipelines import (  # noqa: E402
    DEFAULT_BASE_PORT,
    PIPELINE_OFFSETS,
    PIPELINES,
    read_port_lock,
    verify_pipeline_edges,
)
from uqf_stack.model.registry import render_port_lock  # noqa: E402
from uqf_stack.paths import PROCESS_PORTS_FILE, TABLES_FILE, default_paths  # noqa: E402
from uqf_stack.stack import procs  # noqa: E402

OUT = REPO / "docs" / "integrations" / "torq" / "processes.md"
DAG_OUT = REPO / "src" / "etl" / "generated" / "pipeline_dag.q"
PORTS_OUT = REPO / PROCESS_PORTS_FILE

BANNER = """<!-- GENERATED BY scripts/generate/generate_operational_docs.py - DO NOT EDIT -->
<!-- Run `python3 scripts/generate/generate_operational_docs.py` to regenerate.    -->
<!-- CI runs it with --check; an edit here fails the build.   -->
"""


def _vendored_procnames() -> list[str]:
    """The vendored process.csv rows, minus uqf's own.

    Read rather than remembered: `docs/integrations/torq/README.md` says "the vendored
    14-process stack" in prose, and a number in prose is a number nobody
    re-counts.
    """
    ours = {p.procname for p in PIPELINES}
    rows = procs._base_process_rows(default_paths())
    return [r["procname"] for r in rows if r["procname"] not in ours]


def _schema_names() -> dict[str, str]:
    """Table name -> where it is defined, for the schema section."""
    return {table: f"`{TABLES_FILE.name}`" for table in schemas._definitions()}


def render() -> str:
    problems = verify_pipeline_edges(REPO / "scripts")
    if problems:
        raise SystemExit(
            "refusing to generate: the declared dataflow edges disagree with the "
            "q scripts, so any diagram from them would be confidently wrong.\n  "
            + "\n  ".join(problems)
        )

    vendored = _vendored_procnames()
    schema_of = _schema_names()
    lines: list[str] = [BANNER, "# uqf stack processes", ""]
    lines += [
        "Derived from `uqf_stack.model.pipelines.PIPELINES` and the vendored",
        "`process.csv`. For how to start, stop and query the stack see",
        "[docs/guides/uqf-stack.md](../../guides/uqf-stack.md); for the topology diagrams see",
        "[README.md](README.md).",
        "",
        f"**{len(vendored)} vendored processes** plus **{len(PIPELINES)} uqf processes**"
        f" — {len(vendored) + len(PIPELINES)} in total. Ports are shown at the default"
        f" base port {DEFAULT_BASE_PORT}; every one is `{{KDBBASEPORT}}+offset`, so a"
        " different base shifts them all together.",
        "",
        "## uqf's own processes",
        "",
        "| process | port | kind | script | owns table | subscribes to | publishes |",
        "|---|---|---|---|---|---|---|",
    ]
    # PIPELINE_OFFSETS, not Pipeline.offset: `offset` is None for every
    # auto-allocated pipeline (only fxfeed1 pins one, to the single gap the
    # vendored csv leaves), and the resolved value is what PIPELINE_OFFSETS
    # exists to provide. Sorting on the raw field threw comparing None to int.
    for p in sorted(PIPELINES, key=lambda x: PIPELINE_OFFSETS[x.procname]):
        subs = (
            "_chosen at runtime_"
            if p.subscribes_dynamic
            else (", ".join(f"`{t}`" for t in p.subscribed_tables) or "—")
        )
        pubs = ", ".join(f"`{t}`" for t in p.published_tables) or "—"
        owns = f"`{p.table}`" if p.table else "—"
        lines.append(
            f"| `{p.procname}` | {DEFAULT_BASE_PORT + PIPELINE_OFFSETS[p.procname]} | {p.kind} | "
            f"`{p.script}` | {owns} | {subs} | {pubs} |"
        )

    notes = [
        (p.procname, p.note)
        for p in sorted(PIPELINES, key=lambda x: PIPELINE_OFFSETS[x.procname])
        if p.note
    ]
    if notes:
        lines += ["", "### Why a row deviates from the defaults", ""]
        lines += [f"- **`{name}`** — {note}" for name, note in notes]

    lines += [
        "",
        "## Tables these processes publish",
        "",
        "| table | defined by | published by |",
        "|---|---|---|",
    ]
    publishers: dict[str, list[str]] = {}
    for p in PIPELINES:
        for t in p.published_tables:
            publishers.setdefault(t, []).append(p.procname)
    for table in sorted(publishers):
        const = schema_of.get(table)
        defined = const or "_vendored_"
        who = ", ".join(f"`{n}`" for n in sorted(publishers[table]))
        lines.append(f"| `{table}` | {defined} | {who} |")

    lines += [
        "",
        "## The vendored stack",
        "",
        "Unmodified TorQ Finance Starter Pack processes. uqf never edits the",
        "vendored `process.csv`; `bootstrap()` regenerates an overlay copy that",
        "appends the rows above (ETL-17).",
        "",
        ", ".join(f"`{n}`" for n in vendored),
        "",
    ]
    # rstrip before the final newline, so the output ends with exactly one.
    # The section builders append "" as a spacer, which produced a trailing
    # blank line - and pre-commit's end-of-file-fixer then stripped it,
    # leaving the committed file one byte different from what the generator
    # produces and making --check report it stale forever. Two gates
    # disagreeing, and the right fix is for the generator to emit what the
    # hygiene hooks accept rather than to exempt the file from them.
    return "\n".join(lines).rstrip("\n") + "\n"


Q_BANNER = """/ GENERATED BY scripts/generate/generate_operational_docs.py - DO NOT EDIT.
/ .
/ Run `python3 scripts/generate/generate_operational_docs.py` to regenerate; CI runs
/ it with --check, so an edit here fails the build.
/ .
/ The nine TorQ streaming processes, as .qdag job registrations, so the job
/ graph is complete inside q and a DAG can be ordered or drawn with no
/ Python in the path.
/ .
/ GENERATED rather than hand-written because the Python
/ Pipeline registry is the source of truth. Re-declaring these edges in q by
/ hand would make a second place for them to be wrong; deriving them the
/ other way would contradict the registry. A generated
/ bridge is the only option that keeps one authority.
/ .
/ A FUNCTION rather than bare statements at load time: .qdag.reset[] would
/ otherwise wipe these with no way to get them back, and a test that resets
/ the registry could not restore the real graph.
"""


def _q_symbol_list(names: tuple[str, ...]) -> str:
    """A q symbol-vector literal. `$() for empty - not (), which is a general
    empty list and would give the column the wrong type on the way in.
    """
    if not names:
        return "`$()"
    return "".join(f"`{n}" for n in names)


def render_dag() -> str:
    """The streaming half of the job graph, as q."""
    problems = verify_pipeline_edges(default_paths().scripts_dir)
    if problems:
        raise SystemExit(
            "refusing to generate: the registry and the q scripts disagree:\n  "
            + "\n  ".join(problems)
        )

    lines = [
        Q_BANNER,
        "",
        "/ Register the nine TorQ streaming processes into the job graph.",
        "/ @return the process names registered",
        "/ @eg .qdag.register_pipelines[]",
        ".qdag.register_pipelines:{[]",
    ]
    for pipeline in PIPELINES:
        lines.append(
            f"    .qdag.register[`{pipeline.procname};`kind`inputs`outputs!"
            f"(`{'normalizer' if pipeline.kind == 'normalizer' else 'stream'};"
            f"{_q_symbol_list(pipeline.subscribed_tables)};"
            f"{_q_symbol_list(pipeline.published_tables)})];"
        )
    names = "".join(f"`{p.procname}" for p in PIPELINES)
    lines.append(f"    {names}}}")
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="diff against the committed file")
    args = ap.parse_args()

    # Three outputs, one gate. All derive from PIPELINES, so checking only
    # one would let another drift - the q bridge is the one a running process
    # depends on, and the port lock is what keeps a new process from moving
    # every port after it: a process the lock lacks fails --check here until
    # its offset is written down.
    ports = render_port_lock(read_port_lock(REPO), PIPELINE_OFFSETS)
    outputs = ((OUT, render()), (DAG_OUT, render_dag()), (PORTS_OUT, ports))

    if not args.check:
        for path, generated in outputs:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(generated)
            print(f"wrote {path.relative_to(REPO)}")
        return 0

    stale = 0
    for path, generated in outputs:
        rel = path.relative_to(REPO)
        if not path.is_file():
            print(f"{rel} does not exist - run without --check", file=sys.stderr)
            stale += 1
            continue
        committed = path.read_text()
        if committed == generated:
            print(f"{rel} matches the registry")
            continue
        print(f"{rel} is stale - rerun the generator:", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                committed.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile="committed",
                tofile="generated",
            )
        )
        stale += 1
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
