"""process.csv composition and per-process config overrides.

The precedence, decided as the question bank and asserted by
test_core.test_the_process_csv_layers_compose_in_a_stated_order:

    vendored process.csv  ->  PIPELINES  (appended)
    then process_overrides.csv applied LAST, per procname, field by field

with one field-level overlay on the vendored rows themselves
(VENDORED_STARTWITHALL_OVERLAY, below) sitting at the first step, since it
stands in for editing a file this tree may not edit.

So an override wins over every other source, and the vendored file is never
edited - every run regenerates the merged copy from scratch."""

from __future__ import annotations

import csv
import re
from string import Template

from uqs.logger import get_logger
from uqs.model.pipelines import PROCESS_CSV_FIELDS, _pipeline_rows
from uqs.model.registry import DEFAULT_BASE_PORT
from uqs.paths import UqsError, UqsPaths
from uqs.stack.env import build_env
from uqs.stack.monitor_budget import (
    monitor_connection_extras,
)

log = get_logger(__name__)

# Vendored rows this tree deliberately starts with the stack, against the
# upstream default. One entry so far:
#
#   monitor1 - TorQ ships it startwithall=0, so out of the box nothing runs
#   `.hb.checkheartbeat` and `.hb.hb` is a table nobody fills. Every process
#   still PUBLISHES its heartbeat regardless; the collector is the missing
#   half. `uqs summary`'s Heartbeat column, and the frontend health
#   view behind it, therefore reported "not collected" on a fully healthy
#   stack - a monitoring surface that is only ever populated if an operator
#   knows to start one more process by hand is not monitoring.
#
#   feed1 - the starter pack's random demo feed, turned OFF. It publishes
#   `trade` and `quote`, and this tree has its own producer for `quote`
#   (fxfeed1) built from the FX curve rather than from `rand`. Keeping both
#   meant two feeds interleaving rows into one table, and it cost one of the
#   sixteen inbound connections the licence allows a q process - which is the
#   budget that decides whether fxpositions1 and executions1 can reach the
#   plant at all (#285, LICENCE_CONNECTION_LIMIT). Start it by hand for a
#   vendored TorQ demo.
#
# This is an overlay, not an edit: the vendored file is never touched,
# and because process_overrides.csv is still applied afterwards, an operator
# who does want the upstream behaviour can put it back with
# `uqs config-set monitor1 startwithall 0`.
VENDORED_STARTWITHALL_OVERLAY = {"monitor1": "1", "feed1": "0"}

#: Extra q the gateway loads, appended to its vendored `load` column.
#:
#: `.qcat` is the desk catalog's authored half - what each table is for, and
#: which are deliberately not browsable. It has to answer on the process the
#: BFF already talks to, and that is the gateway: `Gateway.call` runs a
#: program on the gateway process itself, while `route` reaches the data
#: tiers. The columns and types come from the tiers via `meta`; only the
#: prose lives here.
#:
#: Not the generated database.q, which would have been the obvious carrier:
#: only stp1 is given `-schemafile`, so nothing else would see it.
#:
#: The same overlay reasoning as VENDORED_STARTWITHALL_OVERLAY above - the
#: vendored row says `${KDBCODE}/processes/gateway.q` and this appends to it
#: rather than replacing it, because the `load` column takes a
#: space-separated list and the vendored script must still load first.
VENDORED_LOAD_OVERLAY = {"gateway1": "processes/uqs_catalog.q"}


def _base_process_rows(paths: UqsPaths) -> list[dict[str, str]]:
    """The vendored process.csv rows, plus one row per PIPELINES entry
    appended (with stp1's -schemafile extras repointed and
    VENDORED_STARTWITHALL_OVERLAY applied) - the FILE is never mutated,
    always read fresh from the vendored file. The nine uqf rows used to be
    nine literal dicts here; they are generated by _pipeline_rows() now, so
    a new pipeline is a Pipeline() entry rather than an edit to this
    function.
    """
    vendored_procs = paths.torqapphome / "appconfig" / "process.csv"
    with vendored_procs.open(newline="") as f:
        rows = list(csv.DictReader(f))
    appended = _pipeline_rows()
    # monitor1's budget is decided against the WHOLE fleet, not just the
    # vendored half - the uqf pipelines are most of what it would dial out
    # to. Built before the loop because the overlay below needs it, and the
    # startwithall overlay has to be applied first or monitor1's own row
    # would be counted as not starting.
    for row in rows:
        if row["procname"] in VENDORED_STARTWITHALL_OVERLAY:
            row["startwithall"] = VENDORED_STARTWITHALL_OVERLAY[row["procname"]]
        if row["procname"] in VENDORED_LOAD_OVERLAY:
            extra = VENDORED_LOAD_OVERLAY[row["procname"]]
            row["load"] = f"{row['load']} ${{UQFSCRIPTS}}/{extra}".strip()
    for row in rows:
        # stp1 loads its schema via -schemafile in `extras`; point it at the
        # generated copy (vendored database.q + uqf's own `quotes` table -
        # see _generated_schema_content()) instead of the vendored file
        # itself, same never-edit-the-vendored-tree approach as process.csv.
        if row["procname"] == "stp1":
            row["extras"] = row["extras"].replace(
                "${TORQAPPHOME}/database.q", "${TORQDATA}/database.q"
            )
        if row["procname"] == "monitor1":
            extras = monitor_connection_extras(paths, rows + appended)
            if extras:
                row["extras"] = " ".join(x for x in (row["extras"], extras) if x)
    rows.extend(appended)
    return rows


def _read_overrides(paths: UqsPaths) -> dict[str, dict[str, str]]:
    """{procname: {field: value}} from process_overrides.csv, or {} if it
    doesn't exist yet (nothing has been set())."""
    if not paths.overrides_path.is_file():
        return {}
    overrides: dict[str, dict[str, str]] = {}
    with paths.overrides_path.open(newline="") as f:
        for row in csv.DictReader(f):
            overrides.setdefault(row["procname"], {})[row["field"]] = row["value"]
    return overrides


def _write_overrides(paths: UqsPaths, overrides: dict[str, dict[str, str]]) -> None:
    paths.orchestrator_dir.mkdir(parents=True, exist_ok=True)
    with paths.overrides_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["procname", "field", "value"], lineterminator="\n")
        writer.writeheader()
        for procname, fields in overrides.items():
            for field, value in fields.items():
                writer.writerow({"procname": procname, "field": field, "value": value})


def list_process_names(paths: UqsPaths) -> list[str]:
    return [row["procname"] for row in _base_process_rows(paths)]


def assert_known_procnames(paths: UqsPaths, procs: str) -> None:
    """Refuse a lifecycle selector naming a process that does not exist.

    `start`/`stop`/`restart`/`print` used to hand `procs` straight to the
    vendored torq.sh on the grounds that it owns its own handling of an
    unknown name. It does, but badly, and the cost is paid before you see it:
    `uqs start xyz` first printed a licence-cap warning whose arithmetic
    counted the nonexistent process, then the vendored script's own
    `hostname: illegal option` noise, then `xyz failed - unavailable
    processname` - and **exited 0**, so nothing scripting this could tell the
    typo from a successful start.

    Checking here costs one read of the process table and turns all of that
    into one line before any work happens. `all` is passed through untouched:
    it is torq.sh's own selector for the startwithall rows, not a process.

    Deliberately NOT a resolver - it returns nothing and rewrites nothing,
    because `all` has to reach torq.sh as the literal word. `resolve_procnames`
    in stack/logs.py is the sibling that DOES expand, because the log commands
    need a concrete file list.
    """
    if procs.strip() == "all":
        return
    known = list_process_names(paths)
    unknown = [name for name in procs.split() if name not in known]
    if unknown:
        raise UqsError(
            f"unknown process(es) {unknown} - known processes are {known}. "
            "Nothing was started or stopped."
        )


def list_process_choices(paths: UqsPaths) -> list[dict[str, str]]:
    """Every process a lifecycle selector may name, with what a picker shows.

    procname, proctype and startwithall, from the same effective rows torq.sh
    starts from - vendored process.csv and the pipelines -
    with process_overrides.csv applied, so a startwithall a user set through
    config-set is the one reported. Nothing is resolved beyond that: a picker
    needs to know what CAN be started and which are started by "all", not
    what port each would take.
    """
    overrides = _read_overrides(paths)
    out: list[dict[str, str]] = []
    for row in _base_process_rows(paths):
        merged = {**row, **overrides.get(row["procname"], {})}
        out.append(
            {
                "procname": merged["procname"],
                "proctype": merged["proctype"],
                "startwithall": merged.get("startwithall", ""),
            }
        )
    return out


# process.csv's two placeholder styles: `${VAR}` / `$VAR` (shell parameter
# expansion, resolved via envsubst at runtime - handled here by
# string.Template, which uses the same syntax) inside e.g. `load`/`U`/
# `extras`; and `{VAR}` / `{VAR}+N` / `{VAR}-N` (no `$`, only ever in
# `port` - resolved at runtime by torq.sh stripping the braces and letting
# bash arithmetic-context evaluate the bare variable name plus offset).
_BRACE_ARITH_RE = re.compile(r"^\{(\w+)\}([+-]\d+)?$")


def _resolve_value(value: str, env: dict[str, str]) -> str:
    m = _BRACE_ARITH_RE.match(value)
    if m:
        var, offset = m.groups()
        if var in env and env[var].lstrip("-").isdigit():
            return str(int(env[var]) + int(offset or 0))
        return value  # unknown/non-numeric var - leave the placeholder as-is
    return Template(value).safe_substitute(env)


def resolve_process_config(row: dict[str, str], env: dict[str, str]) -> dict[str, str]:
    return {field: _resolve_value(value, env) for field, value in row.items()}


def get_process_config(
    paths: UqsPaths,
    procname: str,
    base_port: int = DEFAULT_BASE_PORT,
    resolve: bool = True,
) -> dict[str, str]:
    """The effective process.csv row for *procname* - vendored/fxfeed1 values
    with any set_process_config() overrides applied on top. With
    resolve=True (the default), also evaluates ${VAR}-style and
    {VAR}(+N)-style placeholders (KDBBASEPORT, KDBHDB, UQFSCRIPTS, ...)
    against build_env(paths, base_port) - the same values torq.sh itself
    would substitute at process-start time.
    """
    rows = {row["procname"]: row for row in _base_process_rows(paths)}
    if procname not in rows:
        raise UqsError(f"unknown process {procname!r} - {sorted(rows)}")
    row = dict(rows[procname])
    row.update(_read_overrides(paths).get(procname, {}))
    if resolve:
        row = resolve_process_config(row, build_env(paths, base_port=base_port))
    return row


def set_process_config(paths: UqsPaths, procname: str, field: str, value: str) -> None:
    """Persist a process.csv field override for *procname*, applied by every
    later bootstrap() (i.e. every start/stop/summary/... call) until
    changed again. Read-modify-write against process_overrides.csv - the
    only file this touches; the vendored process.csv is never edited.
    """
    if field not in PROCESS_CSV_FIELDS:
        raise UqsError(f"unknown process.csv field {field!r} - {PROCESS_CSV_FIELDS}")
    if procname not in list_process_names(paths):
        raise UqsError(f"unknown process {procname!r} - {list_process_names(paths)}")

    overrides = _read_overrides(paths)
    overrides.setdefault(procname, {})[field] = value
    _write_overrides(paths, overrides)
    log.info("set {}.{} = {}", procname, field, value)
