"""wizard.py - interactive console wizard for adding a new TorQ demo
process (see docs/torq-demo.md, and the torq-developer skill's PROCESS
SETUP GUIDE / Stage 1 plumbing checklist this mirrors).

Prompts for the handful of decisions a new process actually needs (name,
publish vs. subscribe, which table, port), writes a Stage-1-only skeleton
.q file - connects and logs, no business logic, exactly what the skill's
Stage 1 mandates - registers it via core.add_extra_process(), and
optionally starts it immediately to run the Stage 1 verification checklist
live (err log empty, process shows up). Stage 2 (the actual publish/
subscribe logic) is left for you to fill in by hand afterwards, mirroring
scripts/torq_fx_feed.q / torq_quotes_feed.q (publisher) or
torq_cross_etl.q (subscriber) - all three link from the generated
skeleton's own header comment.

Kept as its own module, not folded into cli.py (a thin-command-wrapper
file; this is a multi-step interactive flow with its own state - a
different shape of code) or core.py (interactive prompting isn't pure
logic, which is core.py's whole reason for existing).
"""

from __future__ import annotations

import time

from rich.console import Console
from rich.prompt import Confirm, IntPrompt, Prompt

from torq_orchestrator import core

console = Console()

_KNOWN_TABLES = ("quote", "trade", "quotes")

# Stage 1 only (torq-developer skill's PROCESS SETUP GUIDE): connect and
# log, no publish logic yet - copy scripts/torq_fx_feed.q's or
# torq_quotes_feed.q's shape in for Stage 2.
_PUBLISHER_TEMPLATE = """\
/ torq_{procname}.q - Stage 1 skeleton for a new TorQ demo publisher
/ process (see docs/torq-demo.md), generated by `torq-demo new-process`.
/ Discovers the tickerplant and defines a `run` stub that only logs - no
/ publish logic yet. Fill in `run` to actually publish rows into
/ `{table}` (and add a `.timer.repeat` call to fire it on a schedule),
/ mirroring scripts/torq_fx_feed.q or scripts/torq_quotes_feed.q's shape -
/ both publish via a self-managed .servers.gethandlebytype handle, no
/ .servers.startup[]/credentials needed for that.
/ .
/ Not loaded by src/init.q or anything else uqf itself runs - registered
/ only in process_overrides-style extra_processes.csv (see core.py's
/ add_extra_process()), port {{KDBBASEPORT}}+{port_offset}.

run:{{[] .lg.o[`run;"stub - fill in {table} publish logic, see torq_fx_feed.q for the shape"]}}

/- use the discovery service to find the tickerplant to publish data to,
/  exactly as feed.q/torq_fx_feed.q/torq_quotes_feed.q do
.servers.startupdepcycles[`segmentedtickerplant;10;0W];
h:.servers.gethandlebytype[`segmentedtickerplant;`any];

/ Uncomment once `run` actually publishes something:
/ .timer.repeat[.proc.cp[];0Wp;0D00:00:01.000;(`run;`);"{procname}"];

run[];
"""

# Stage 1 only, mirroring scripts/torq_cross_etl.q's already-verified
# subscribe setup exactly (tickerplanttypes/requiredprocs/subscribe/init
# shape, .servers.CONNECTIONS + .servers.startup[] at the end) - just with
# `upd` reduced to a log line instead of cross_etl's mirror-table+reprice
# logic. .servers.startup[] (unlike the publisher template above) needs a
# real handle+credentials, since .sub.subscribe requires a .servers-managed
# connection, not a self-managed one - hence `U` pointing at
# accesslist.txt (see core.py's add_extra_process call in cli.py).
_SUBSCRIBER_TEMPLATE = """\
/ torq_{procname}.q - Stage 1 skeleton for a new TorQ demo subscriber
/ process (see docs/torq-demo.md), generated by `torq-demo new-process`.
/ Subscribes to `{table}` from the tickerplant and defines a root `upd`
/ that only logs each batch - no processing logic yet. Fill in `upd` to
/ actually do something with incoming rows, mirroring
/ scripts/torq_cross_etl.q's shape (mirror table + derived-table pipeline).
/ .
/ Not loaded by src/init.q or anything else uqf itself runs - registered
/ only in process_overrides-style extra_processes.csv (see core.py's
/ add_extra_process()), port {{KDBBASEPORT}}+{port_offset}.

\\d .{procname}

tickerplanttypes:`segmentedtickerplant
requiredprocs:tickerplanttypes
tpconsleep:10
tpcheckcycles:0W

subscribe:{{
  if[0=count s:.sub.getsubscriptionhandles[tickerplanttypes;();()!()];:()];
  subproc:first s;
  .lg.o[`subscribe;"subscribing to ",string subproc`procname];
  .sub.subscribe[`{table};`;0b;0b;subproc]
 }}

init:{{
  .servers.startupdepcycles[requiredprocs;tpconsleep;tpcheckcycles];
  subscribe[];
 }}

\\d .

upd:{{[t;x]
  if[t=`{table};
    n:string count x[0];
    .lg.o[`upd;"received batch for ",string[t]," - ",n," rows (stub, not processed yet)"]];
 }}

.servers.CONNECTIONS:.{procname}.requiredprocs;
.servers.startup[];
.{procname}.init[];
"""


def _prompt_procname(paths: core.TorqDemoPaths) -> str:
    existing = core.list_process_names(paths)
    while True:
        name = Prompt.ask("Process name (e.g. myfeed1)").strip()
        if not name:
            console.print("[red]required[/]")
            continue
        if name in existing:
            console.print(f"[red]{name!r} already exists[/] - pick another name")
            continue
        return name


def _prompt_table(kind: str) -> str:
    console.print(f"Known tables: {', '.join(_KNOWN_TABLES)} (or type a new name)")
    verb = "publish into" if kind == "publisher" else "subscribe to"
    return Prompt.ask(f"Table to {verb}", default="quotes").strip()


def _prompt_port_offset(paths: core.TorqDemoPaths) -> int:
    suggested = core.next_free_port_offset(paths)
    return IntPrompt.ask("Port offset ({KDBBASEPORT}+N)", default=suggested)


def _write_skeleton(
    paths: core.TorqDemoPaths, procname: str, kind: str, table: str, port_offset: int
):
    template = _PUBLISHER_TEMPLATE if kind == "publisher" else _SUBSCRIBER_TEMPLATE
    content = template.format(procname=procname, table=table, port_offset=port_offset)
    dest = paths.scripts_dir / f"torq_{procname}.q"
    dest.write_text(content)
    return dest


def _build_row(procname: str, kind: str, port_offset: int, load_path: str) -> dict[str, str]:
    return {
        "host": "localhost",
        "port": f"{{KDBBASEPORT}}+{port_offset}",
        "proctype": "feed" if kind == "publisher" else "metrics",
        "procname": procname,
        # Subscribers need a real .servers-managed, credentialed handle
        # (see _SUBSCRIBER_TEMPLATE's comment); publishers self-manage
        # their own handle via .servers.gethandlebytype and need none.
        "U": "" if kind == "publisher" else "${TORQAPPHOME}/appconfig/passwords/accesslist.txt",
        "localtime": "1",
        "g": "0",
        "T": "",
        "w": "",
        "load": load_path,
        "startwithall": "1",
        "extras": "",
        "qcmd": "q",
    }


def _verify_stage1(paths: core.TorqDemoPaths, procname: str, base_port: int) -> None:
    console.print(f"\n[bold]Starting {procname} for Stage 1 verification...[/]")
    core.start(paths, procs=procname, base_port=base_port, capture=True)
    time.sleep(3)

    err_log = paths.torqdata / "logs" / f"err_{procname}.log"
    if err_log.is_file() and err_log.read_text(errors="replace").strip():
        console.print(f"[bold red]FAIL[/] {err_log.name} is not empty:")
        console.print(err_log.read_text(errors="replace"))
    else:
        console.print(f"[bold green]OK[/]   {err_log.name} is empty")

    result = core.summary(paths, base_port=base_port)
    up = any(
        procname in line and "|up|" in line.replace(" ", "").lower()
        for line in result.stdout.splitlines()
    )
    if up:
        console.print(f"[bold green]OK[/]   {procname} shows up in summary")
    else:
        console.print(f"[bold red]FAIL[/] {procname} does not show as up - see `torq-demo summary`")

    console.print(
        "\nRemaining checklist items from the torq-developer skill's Stage 1 "
        f"Verification (check by hand): `.servers.SERVERS` has a non-null `w` "
        f"for every entry in `.servers.CONNECTIONS`; if subscribing, "
        f"`.sub.SUBSCRIPTIONS` shows `{procname}`'s table and the tickerplant's "
        f"`exec w from .u.w.<table>` includes its handle. "
        f"`torq-demo raw -- qcon {procname} admin:admin` to check interactively."
    )


def run(paths: core.TorqDemoPaths, base_port: int = core.DEFAULT_BASE_PORT) -> None:
    console.print("[bold]torq-demo new-process[/] - add a new TorQ demo process\n")

    procname = _prompt_procname(paths)
    publishes = Confirm.ask("Does it publish rows to the tickerplant?", default=True)
    kind = "publisher" if publishes else "subscriber"
    table = _prompt_table(kind)
    port_offset = _prompt_port_offset(paths)

    skeleton_path = _write_skeleton(paths, procname, kind, table, port_offset)
    load_path = "${UQFSCRIPTS}/" + skeleton_path.name
    row = _build_row(procname, kind, port_offset, load_path)

    console.print(f"\nSkeleton written to [cyan]{skeleton_path}[/]")
    console.print(
        f"process.csv row: port {{KDBBASEPORT}}+{port_offset}, proctype {row['proctype']!r}"
    )
    if not Confirm.ask("Register this process?", default=True):
        console.print("Aborted - skeleton file kept, nothing registered.")
        return

    core.add_extra_process(paths, row)
    console.print(f"[bold green]Registered[/] {procname} in extra_processes.csv")

    if Confirm.ask("Start it now and run Stage 1 verification?", default=True):
        _verify_stage1(paths, procname, base_port)
    else:
        console.print(f"Skipped - run `torq-demo start {procname}` when ready.")
