"""wizard.py - interactive console wizard for adding a new uqf stack
process (see docs/guides/uqf-stack.md, and the torq-developer skill's PROCESS
SETUP GUIDE / Stage 1 plumbing checklist this mirrors).

Opens with a menu of concrete recipes rather than an abstract "does it
publish or subscribe?" question, so someone with no q/kdb+ knowledge can
pick one and get a genuinely running process - not a stub to hand-finish:

- "FX quotes feed" and "Cross-rate reprice ETL" are fully parametrized
  copies of scripts/torq_quotes_feed.q and scripts/torq_cross_etl.q's own
  working shape (see those files for the un-parametrized originals this
  mirrors) - answer a few prompts (pairs, rates, table names) and the
  generated .q file needs no further editing to do something real.
- "Blank publisher"/"Blank subscriber" are the original Stage-1-only
  skeletons (connects and logs, no business logic) for anyone who wants
  to write their own logic from scratch, mirroring
  scripts/torq_fx_feed.q/torq_quotes_feed.q (publisher) or
  torq_cross_etl.q (subscriber) - both link from the generated skeleton's
  own header comment.

Every recipe still ends the same way: write the .q file, register it via
core.add_extra_process() (and, for a brand-new table, core.
add_extra_table_schema()), and optionally start it immediately to verify
it's actually alive.

Kept as its own module, not folded into cli.py (a thin-command-wrapper
file; this is a multi-step interactive flow with its own state - a
different shape of code) or core.py (interactive prompting isn't pure
logic, which is core.py's whole reason for existing).
"""

from __future__ import annotations

import re
import time
from pathlib import Path

from rich.console import Console
from rich.prompt import Confirm, FloatPrompt, IntPrompt, Prompt

from torq_orchestrator import core

console = Console()

_KNOWN_TABLES = ("quote", "trade", "quotes")

# Used to validate anything that gets spliced into generated q source as a
# bare identifier (procname, a new table name) - not just cosmetic: an
# unvalidated value here would corrupt the generated script (e.g. a space
# or semicolon in a table name breaks the line it's spliced into).
_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# CURCUR convention (see src/foundation/ccy.q's normalize_ccy_pair) - six uppercase
# letters, no separator. Same safety reasoning as _IDENT_RE: a pair name
# gets spliced into a q symbol list literal (`` `EURUSD`GBPUSD ``)
# unquoted, so it must already be validated, not just uppercased.
_PAIR_RE = re.compile(r"^[A-Z]{6}$")

_RECIPES: dict[str, tuple[str, str]] = {
    "1": (
        "quotes_feed",
        "FX quotes feed - publish quotes for currency pairs you pick "
        "[green](ready to run, no q editing)[/]",
    ),
    "2": (
        "cross_etl",
        "Cross-rate reprice ETL - watch a quotes table and reprice synthetic "
        "cross pairs you pick [green](ready to run, no q editing)[/]",
    ),
    "3": (
        "blank_publisher",
        "Blank publisher - write your own row-generating process from scratch "
        "[yellow](for q/kdb+ users)[/]",
    ),
    "4": (
        "blank_subscriber",
        "Blank subscriber - write your own table-watching process from scratch "
        "[yellow](for q/kdb+ users)[/]",
    ),
}

# Stage 1 only (torq-developer skill's PROCESS SETUP GUIDE): connect and
# log, no publish logic yet - copy scripts/torq_fx_feed.q's or
# torq_quotes_feed.q's shape in for Stage 2.
_PUBLISHER_TEMPLATE = """\
/ torq_{procname}.q - Stage 1 skeleton for a new uqf stack publisher
/ process (see docs/guides/uqf-stack.md), generated by `uqf-stack new-process`.
/ Discovers the tickerplant and defines a `run` stub that only logs - no
/ publish logic yet. Fill in `run` to actually publish rows into
/ `{table}` (and add a `.timer.repeat` call to fire it on a schedule),
/ mirroring scripts/torq_fx_feed.q or scripts/torq_quotes_feed.q's shape -
/ both publish via a self-managed .servers.gethandlebytype handle, no
/ .servers.startup[]/credentials needed for that.
/ .
/ Not loaded by src/init.q or anything else uqf itself runs - registered
/ only in process_overrides-style extra_processes.csv (see core.py's
/ add_extra_process()), port {{KDBBASEPORT}}+{port_offset}.

run:{{[] .lg.o[`run;"stub - fill in {table} publish logic, see torq_fx_feed.q for the shape"]}}

/- use the discovery service to find the tickerplant to publish data to,
/  exactly as feed.q/torq_fx_feed.q/torq_quotes_feed.q do
.servers.startupdepcycles[`segmentedtickerplant;10;0W];
h:.servers.gethandlebytype[`segmentedtickerplant;`any];

/ Uncomment once `run` actually publishes something:
/ .timer.repeat[.proc.cp[];0Wp;0D00:00:01.000;(`run;`);"{procname}"];

run[];
"""

# Stage 1 only, mirroring scripts/torq_cross_etl.q's already-verified
# subscribe setup exactly (tickerplanttypes/requiredprocs/subscribe/init
# shape, .servers.CONNECTIONS + .servers.startup[] at the end) - just with
# `upd` reduced to a log line instead of cross_etl's mirror-table+reprice
# logic. .servers.startup[] (unlike the publisher template above) needs a
# real handle+credentials, since .sub.subscribe requires a .servers-managed
# connection, not a self-managed one - hence `U` pointing at
# accesslist.txt (see core.py's add_extra_process call in cli.py).
_SUBSCRIBER_TEMPLATE = """\
/ torq_{procname}.q - Stage 1 skeleton for a new uqf stack subscriber
/ process (see docs/guides/uqf-stack.md), generated by `uqf-stack new-process`.
/ Subscribes to `{table}` from the tickerplant and defines a root `upd`
/ that only logs each batch - no processing logic yet. Fill in `upd` to
/ actually do something with incoming rows, mirroring
/ scripts/torq_cross_etl.q's shape (mirror table + derived-table pipeline).
/ .
/ Not loaded by src/init.q or anything else uqf itself runs - registered
/ only in process_overrides-style extra_processes.csv (see core.py's
/ add_extra_process()), port {{KDBBASEPORT}}+{port_offset}.

\\d .qsub.{procname}

tickerplanttypes:`segmentedtickerplant
requiredprocs:tickerplanttypes
tpconsleep:10
tpcheckcycles:0W

subscribe:{{
  if[0=count s:.sub.getsubscriptionhandles[tickerplanttypes;();()!()];:()];
  subproc:first s;
  .lg.o[`subscribe;"subscribing to ",string subproc`procname];
  .sub.subscribe[`{table};`;0b;0b;subproc]
 }}

init:{{
  .servers.startupdepcycles[requiredprocs;tpconsleep;tpcheckcycles];
  subscribe[];
 }}

\\d .

upd:{{[t;x]
  if[t=`{table};
    n:string count x[0];
    .lg.o[`upd;"received batch for ",string[t]," - ",n," rows (stub, not processed yet)"]];
 }}

.servers.CONNECTIONS:.qsub.{procname}.requiredprocs;
.servers.startup[];
.qsub.{procname}.init[];
"""

# Fully working (not a stub) - a parametrized copy of
# scripts/torq_quotes_feed.q. Publishes into a brand-new table (registered
# separately via core.add_extra_table_schema), so it never collides with
# the standing quotesfeed1 process's own `quotes` table.
_QUOTES_FEED_TEMPLATE = """\
/ torq_{procname}.q - FX quotes feed, generated by `uqf-stack new-process`
/ (recipe: FX quotes feed). Publishes synthetic depth-aware quotes for
/ {pairs_display} into `{table}` every 500ms - ready to run as-is, no
/ further q editing needed. Same shape/pattern as
/ scripts/torq_quotes_feed.q (see docs/guides/uqf-stack.md); pip size per pair is
/ 0.01 for JPY crosses, 0.0001 otherwise (see wizard.py's _pip_size).
/ .
/ Not loaded by src/init.q or anything else uqf itself runs - registered
/ only in process_overrides-style extra_processes.csv (see core.py's
/ add_extra_process()), port {{KDBBASEPORT}}+{port_offset}.

/ pairs/spot/pip are parallel plain vectors, not a dict - a dict here
/ would silently turn the level columns into dicts too, which .u.upd
/ rejects with a length error on insert (see torq_quotes_feed.q's own
/ comment on this).
pairs:{pairs_lit}
spot:{spot_lit}
pip:{pip_lit}
size_unit:1000000
n_levels:3

/ small symmetric random walk per tick, +/-5bp of current spot
drift_one:{{[s] s*1+0.0005*-1+2*rand 1f}}

/ Level-0-first price vector for one pair: n_levels prices, `step` apart,
/ starting one step away from mid.
levels_one:{{[mid;step;dir] mid+dir*step*1+til n_levels}}

/ Level-0-first size vector: size_unit, 2*size_unit, ... - thinner at the
/ top of book, deeper further away.
levels_size:size_unit*1+til n_levels

publish_quotes:{{[]
 spot::drift_one each spot;
 n:count pairs;
 bid_prices:levels_one[;;-1] .' flip (spot;pip);
 ask_prices:levels_one[;;1] .' flip (spot;pip);
 bid_sizes:n#enlist levels_size;
 ask_sizes:n#enlist levels_size;
 h (`.u.upd;`{table};(pairs;bid_prices;bid_sizes;ask_prices;ask_sizes))
 }}

/- use the discovery service to find the tickerplant to publish data to,
/  exactly as feed.q/torq_fx_feed.q/torq_quotes_feed.q do
.servers.startupdepcycles[`segmentedtickerplant;10;0W];
h:.servers.gethandlebytype[`segmentedtickerplant;`any];

.timer.repeat[.proc.cp[];0Wp;0D00:00:00.500;(`publish_quotes;`);"{procname}"];
"""

# Fully working (not a stub) - a parametrized copy of
# scripts/torq_cross_etl.q. Subscribes to an existing quotes-shaped table
# (source_table - the standing `quotes` table by default) and reprices
# cross_pairs through uqf's own .qfwd.cross_book_at on every batch. Output
# lands in a private `crossed` table, same as the original's `cross_quotes`
# - not part of the tickerplant schema, so unlike the quotes-feed recipe
# this needs no core.add_extra_table_schema() call.
_CROSS_ETL_TEMPLATE = """\
/ torq_{procname}.q - cross-rate reprice ETL, generated by
/ `uqf-stack new-process` (recipe: cross-rate reprice ETL). Subscribes to
/ `{source_table}` and reprices {pairs_display} through uqf's own
/ .qfwd.cross_book_at (src/pricing/forwards.q) on every batch - ready to run as-is,
/ no further q editing needed. Same shape/pattern as
/ scripts/torq_cross_etl.q (see docs/guides/uqf-stack.md). Results land in a
/ private `crossed` table - query it directly (not through the gateway)
/ with e.g. `uqf-stack query "select from crossed" --port <port>`.
/ .
/ Not loaded by src/init.q or anything else uqf itself runs - registered
/ only in process_overrides-style extra_processes.csv (see core.py's
/ add_extra_process()), port {{KDBBASEPORT}}+{port_offset}.

\\d .qsub.{procname}

/ mirror of {source_table}'s own schema - what this process actually
/ receives via its subscription. A fixed name (not {source_table} itself)
/ since it's purely local - nothing else needs it to match the source
/ table's own name.
mirror:([]time:`timestamp$(); sym:`g#`symbol$(); bid_prices:(); bid_sizes:();
  ask_prices:(); ask_sizes:())

/ this ETL's output: one row per (pair, reprice) - the whole point of the process.
crossed:([]time:`timestamp$(); sym:`symbol$(); bid:`float$(); ask:`float$(); mid:`float$())

cross_pairs:{cross_pairs_lit}
cross_size:{cross_size}

/ recompute every pair in cross_pairs from the current mirror and append
/ the results to crossed - called after every upd[`{source_table};...] batch.
reprice:{{[]
  if[0=count mirror;:()];
  / cross_book_at's required shape: `ts`sym`bid_prices`bid_sizes`ask_prices`ask_sizes, `sym`ts xasc
  q:`sym`ts xasc select ts:time,sym,bid_prices,bid_sizes,ask_prices,ask_sizes from mirror;
  rows:raze {{[q;sym]
    r:.[.qfwd.cross_book_at;(q;sym;.z.p;enlist cross_size;`bid`ask`mid);
      {{[sym;e] .lg.o[`reprice;"skipping ",string[sym],": ",e]; ()}}[sym;]];
    if[0=count r;:()];
    r:first r;
    enlist `time`sym`bid`ask`mid!(.z.p;sym;r`bid;r`ask;r`mid)
   }}[q;] each cross_pairs;
  if[count rows; `.qsub.{procname}.crossed insert rows];
 }}

\\d .

/ receive quotes ticks from the tickerplant subscription and route them
/ into the local mirror, then recompute every cross pair.
upd:{{[t;x]
  if[t=`{source_table}; `.qsub.{procname}.mirror insert x; .qsub.{procname}.reprice[]];
 }}

\\d .qsub.{procname}

tickerplanttypes:`segmentedtickerplant
requiredprocs:tickerplanttypes
tpconsleep:10
tpcheckcycles:0W

subscribe:{{
  if[0=count s:.sub.getsubscriptionhandles[tickerplanttypes;();()!()];:()];
  subproc:first s;
  .lg.o[`subscribe;"subscribing to ",string subproc`procname];
  .sub.subscribe[`{source_table};`;0b;0b;subproc]
 }}

init:{{
  .servers.startupdepcycles[requiredprocs;tpconsleep;tpcheckcycles];
  subscribe[];
 }}

\\d .

/ pull in uqf's own src/init.q (loads .qfwd/.qccy/... - see UQFROOT in
/ core.py's build_env). init.q's own \\l lines are repo-root-relative
/ (`\\l src/foundation/stats.q`, ...), and torq.sh doesn't launch us from the repo
/ root, so cd there for the load and back again immediately after -
/ system"cd ..." is q's own builtin chdir, not a subshell, so it sticks
/ across the two calls.
{{[uqfroot]
  cwd:first system"pwd";
  system"cd ",uqfroot;
  system"l src/init.q";
  system"cd ",cwd;
 }}[getenv[`UQFROOT]];

/ a real .sub.subscribe subscriber needs a live, .servers-managed handle
/ to stp1 - .servers.startup[] is what actually opens and registers that,
/ using this process's own accesslist.txt credentials (see process.csv's
/ `U` field in core.py) to authenticate with discovery1.
.servers.CONNECTIONS:.qsub.{procname}.requiredprocs;
.servers.startup[];
.qsub.{procname}.init[];
"""


def _prompt_recipe() -> str:
    console.print("What do you want to build?\n")
    for key, (_, desc) in _RECIPES.items():
        console.print(f"  [bold]{key}[/]. {desc}")
    console.print()
    choice = Prompt.ask("Choice", choices=list(_RECIPES), default="1")
    return _RECIPES[choice][0]


def _prompt_procname(paths: core.UqfStackPaths) -> str:
    existing = core.list_process_names(paths)
    while True:
        name = Prompt.ask("Process name (e.g. myfeed1)").strip()
        if not name:
            console.print("[red]required[/]")
            continue
        if not _IDENT_RE.match(name):
            console.print(
                "[red]must be letters/digits/underscore, not starting with a digit[/] "
                "(it becomes a q identifier and a file name)"
            )
            continue
        if name in existing:
            console.print(f"[red]{name!r} already exists[/] - pick another name")
            continue
        return name


def _prompt_table(kind: str) -> str:
    console.print(f"Known tables: {', '.join(_KNOWN_TABLES)} (or type a new name)")
    verb = "publish into" if kind == "publisher" else "subscribe to"
    return Prompt.ask(f"Table to {verb}", default="quotes").strip()


def _prompt_table_name(prompt_text: str, default: str) -> str:
    while True:
        name = Prompt.ask(prompt_text, default=default).strip()
        if _IDENT_RE.match(name):
            return name
        console.print(
            "[red]must be letters/digits/underscore, not starting with a digit[/] "
            "(it becomes a q table name)"
        )


def _prompt_port_offset(paths: core.UqfStackPaths) -> int:
    suggested = core.next_free_port_offset(paths)
    return IntPrompt.ask("Port offset ({KDBBASEPORT}+N)", default=suggested)


def _parse_pairs(raw: str) -> list[str]:
    seen: list[str] = []
    for part in re.split(r"[,\s]+", raw.strip()):
        if not part:
            continue
        pair = part.upper()
        if not _PAIR_RE.match(pair):
            raise ValueError(f"{part!r} doesn't look like a 6-letter pair (e.g. EURUSD)")
        if pair not in seen:
            seen.append(pair)
    return seen


def _prompt_pairs(prompt_text: str, default: str) -> list[str]:
    while True:
        raw = Prompt.ask(prompt_text, default=default)
        try:
            pairs = _parse_pairs(raw)
        except ValueError as exc:
            console.print(f"[red]{exc}[/]")
            continue
        if pairs:
            return pairs
        console.print("[red]at least one pair is required[/]")


def _pip_size(pair: str) -> float:
    # JPY crosses quote in 100ths, not the usual 10,000ths - matches the
    # README's "pip_factor is 10000 for most pairs, 100 for JPY crosses".
    return 0.01 if pair.endswith("JPY") else 0.0001


def _prompt_spot_rates(pairs: list[str]) -> dict[str, float]:
    console.print(
        "\nCurrent rate for each pair (just a realistic starting point - "
        "it'll drift randomly from there):"
    )
    spots: dict[str, float] = {}
    for pair in pairs:
        while True:
            rate = FloatPrompt.ask(f"  {pair}")
            if rate > 0:
                spots[pair] = rate
                break
            console.print("[red]must be positive[/]")
    return spots


def _default_table_name(procname: str) -> str:
    stripped = re.sub(r"\d+$", "", procname)
    return stripped if stripped else f"{procname}_quotes"


def _quotes_table_schema(table: str) -> str:
    return (
        f"{table}:([]time:`timestamp$(); sym:`g#`symbol$(); "
        "bid_prices:(); bid_sizes:(); ask_prices:(); ask_sizes:())"
    )


def _write_skeleton(
    paths: core.UqfStackPaths, procname: str, kind: str, table: str, port_offset: int
) -> Path:
    template = _PUBLISHER_TEMPLATE if kind == "publisher" else _SUBSCRIBER_TEMPLATE
    content = template.format(procname=procname, table=table, port_offset=port_offset)
    dest = paths.scripts_dir / f"torq_{procname}.q"
    dest.write_text(content)
    return dest


def _write_quotes_feed_skeleton(
    paths: core.UqfStackPaths,
    procname: str,
    pairs: list[str],
    spots: dict[str, float],
    table: str,
    port_offset: int,
) -> Path:
    content = _QUOTES_FEED_TEMPLATE.format(
        procname=procname,
        pairs_display=", ".join(pairs),
        table=table,
        pairs_lit="`" + "`".join(pairs),
        spot_lit=" ".join(str(spots[pair]) for pair in pairs),
        pip_lit=" ".join(str(_pip_size(pair)) for pair in pairs),
        port_offset=port_offset,
    )
    dest = paths.scripts_dir / f"torq_{procname}.q"
    dest.write_text(content)
    return dest


def _write_cross_etl_skeleton(
    paths: core.UqfStackPaths,
    procname: str,
    source_table: str,
    cross_pairs: list[str],
    cross_size: float,
    port_offset: int,
) -> Path:
    content = _CROSS_ETL_TEMPLATE.format(
        procname=procname,
        source_table=source_table,
        pairs_display=", ".join(cross_pairs),
        cross_pairs_lit="`" + "`".join(cross_pairs),
        cross_size=cross_size,
        port_offset=port_offset,
    )
    dest = paths.scripts_dir / f"torq_{procname}.q"
    dest.write_text(content)
    return dest


def _build_row(procname: str, kind: str, port_offset: int, load_path: str) -> dict[str, str]:
    return {
        "host": "localhost",
        "port": f"{{KDBBASEPORT}}+{port_offset}",
        "proctype": "feed" if kind == "publisher" else "metrics",
        "procname": procname,
        # Subscribers need a real .servers-managed, credentialed handle
        # (see _SUBSCRIBER_TEMPLATE's/_CROSS_ETL_TEMPLATE's comments);
        # publishers self-manage their own handle via
        # .servers.gethandlebytype and need none.
        "U": "" if kind == "publisher" else "${TORQAPPHOME}/appconfig/passwords/accesslist.txt",
        "localtime": "1",
        "g": "0",
        "T": "",
        "w": "",
        "load": load_path,
        "startwithall": "1",
        "extras": "",
        "qcmd": "q",
    }


def _verify_running(paths: core.UqfStackPaths, procname: str, base_port: int) -> bool:
    """Starts procname and checks it's actually alive: empty err log, shows
    up in `summary`. Shared by every recipe - canned or blank - since
    "does it start cleanly" is a universal check, even though what's left
    to do afterward (nothing, vs. Stage 2) differs per recipe.
    """
    console.print(f"\n[bold]Starting {procname}...[/]")
    core.start(paths, procs=procname, base_port=base_port, capture=True)
    time.sleep(3)

    ok = True
    err_log = paths.torqdata / "logs" / f"err_{procname}.log"
    if err_log.is_file() and err_log.read_text(errors="replace").strip():
        console.print(f"[bold red]FAIL[/] {err_log.name} is not empty:")
        console.print(err_log.read_text(errors="replace"))
        ok = False
    else:
        console.print(f"[bold green]OK[/]   {err_log.name} is empty")

    result = core.summary(paths, base_port=base_port)
    up = any(
        procname in line and "|up|" in line.replace(" ", "").lower()
        for line in result.stdout.splitlines()
    )
    if up:
        console.print(f"[bold green]OK[/]   {procname} shows up in summary")
    else:
        console.print(f"[bold red]FAIL[/] {procname} does not show as up - see `uqf-stack summary`")
        ok = False
    return ok


def _print_stage1_todo(procname: str) -> None:
    console.print(
        "\nThis is a Stage 1 skeleton (connects and logs, no business logic yet) - "
        "fill in `run`/`upd` by hand next, mirroring the example linked in the "
        "generated file's own header comment.\n"
        "Remaining checklist items from the torq-developer skill's Stage 1 "
        f"Verification (check by hand): `.servers.SERVERS` has a non-null `w` "
        f"for every entry in `.servers.CONNECTIONS`; if subscribing, "
        f"`.sub.SUBSCRIPTIONS` shows `{procname}`'s table and the tickerplant's "
        f"`exec w from .u.w.<table>` includes its handle. "
        f"`uqf-stack raw -- qcon {procname} admin:admin` to check interactively."
    )


def _confirm_and_register(
    paths: core.UqfStackPaths,
    skeleton_path: Path,
    row: dict[str, str],
    port_offset: int,
    extra_info: str,
    extra_schema: str | None = None,
) -> bool:
    console.print(f"\nSkeleton written to [cyan]{skeleton_path}[/]")
    console.print(
        f"process.csv row: port {{KDBBASEPORT}}+{port_offset}, "
        f"proctype {row['proctype']!r}{extra_info}"
    )
    if not Confirm.ask("Register this process?", default=True):
        console.print("Aborted - skeleton file kept, nothing registered.")
        return False

    core.add_extra_process(paths, row)
    msg = f"[bold green]Registered[/] {row['procname']} in extra_processes.csv"
    if extra_schema is not None:
        core.add_extra_table_schema(paths, extra_schema)
        msg += " and its table in extra_schema.q"
    console.print(msg)
    return True


def _run_quotes_feed(paths: core.UqfStackPaths, base_port: int) -> None:
    procname = _prompt_procname(paths)
    pairs = _prompt_pairs("Currency pairs to quote (e.g. EURUSD, GBPUSD)", "EURUSD, GBPUSD, USDJPY")
    spots = _prompt_spot_rates(pairs)
    table = _prompt_table_name("Table to publish into", _default_table_name(procname))
    port_offset = _prompt_port_offset(paths)

    skeleton_path = _write_quotes_feed_skeleton(paths, procname, pairs, spots, table, port_offset)
    load_path = "${UQFSCRIPTS}/" + skeleton_path.name
    row = _build_row(procname, "publisher", port_offset, load_path)

    registered = _confirm_and_register(
        paths,
        skeleton_path,
        row,
        port_offset,
        f", publishing into `{table}`",
        _quotes_table_schema(table),
    )
    if not registered:
        return

    if not Confirm.ask("Start it now?", default=True):
        console.print(f"Skipped - run `uqf-stack start {procname}` when ready.")
        return
    if _verify_running(paths, procname, base_port):
        console.print(
            f"\n[bold green]Done[/] - {procname} is live and already publishing "
            f"`{table}`, no further q editing needed. Try:\n"
            f'  uqf-stack query "select from {table}" --port {base_port + port_offset}'
        )


def _run_cross_etl(paths: core.UqfStackPaths, base_port: int) -> None:
    procname = _prompt_procname(paths)
    source_table = _prompt_table_name(
        "Table to watch for quotes (must be sym/bid_prices/bid_sizes/ask_prices/"
        "ask_sizes-shaped - the standing `quotes` table always has this shape)",
        "quotes",
    )
    cross_pairs = _prompt_pairs(
        "Synthetic cross pairs to reprice (pairs not already quoted directly, e.g. EURJPY, GBPJPY)",
        "EURJPY, GBPJPY",
    )
    cross_size = FloatPrompt.ask("Size to reprice at", default=1000000)
    port_offset = _prompt_port_offset(paths)

    skeleton_path = _write_cross_etl_skeleton(
        paths, procname, source_table, cross_pairs, cross_size, port_offset
    )
    load_path = "${UQFSCRIPTS}/" + skeleton_path.name
    row = _build_row(procname, "subscriber", port_offset, load_path)

    registered = _confirm_and_register(
        paths, skeleton_path, row, port_offset, f", watching `{source_table}`"
    )
    if not registered:
        return

    if not Confirm.ask("Start it now?", default=True):
        console.print(f"Skipped - run `uqf-stack start {procname}` when ready.")
        return
    if _verify_running(paths, procname, base_port):
        console.print(
            f"\n[bold green]Done[/] - {procname} is live and already repricing "
            f"{', '.join(cross_pairs)}, no further q editing needed. Try:\n"
            f'  uqf-stack query "select from crossed" --port {base_port + port_offset}'
        )


def _run_blank(paths: core.UqfStackPaths, base_port: int, kind: str) -> None:
    procname = _prompt_procname(paths)
    table = _prompt_table(kind)
    port_offset = _prompt_port_offset(paths)

    skeleton_path = _write_skeleton(paths, procname, kind, table, port_offset)
    load_path = "${UQFSCRIPTS}/" + skeleton_path.name
    row = _build_row(procname, kind, port_offset, load_path)

    registered = _confirm_and_register(paths, skeleton_path, row, port_offset, "")
    if not registered:
        return

    if not Confirm.ask("Start it now and run Stage 1 verification?", default=True):
        console.print(f"Skipped - run `uqf-stack start {procname}` when ready.")
        return
    _verify_running(paths, procname, base_port)
    _print_stage1_todo(procname)


def run(paths: core.UqfStackPaths, base_port: int = core.DEFAULT_BASE_PORT) -> None:
    console.print("[bold]uqf-stack new-process[/] - add a new uqf stack process\n")

    recipe = _prompt_recipe()
    if recipe == "quotes_feed":
        _run_quotes_feed(paths, base_port)
    elif recipe == "cross_etl":
        _run_cross_etl(paths, base_port)
    else:
        kind = "publisher" if recipe == "blank_publisher" else "subscriber"
        _run_blank(paths, base_port, kind)
