#!/usr/bin/env python3
"""Generate `docs/man.q`'s registry entries from the qDoc comments in `src/`.

`docs/man.q` calls itself "Generated qdoc tables" on line 1, and its entries
are verbatim copies of the prose above each function in `src/` - so it WAS
generated once. The generator is not in this repository, and the file has
fallen a long way behind:

    348 public q functions
     78 registered in man.q
    273 undocumented - including .qmicro, .qsrc, .qdag, .qbw, .qcov and
        every other ETL namespace at zero coverage

`.man.getDocs[]` is the programmatic documentation API, so that gap is not
cosmetic: a caller asking about `.qcov.is_covered` gets nothing back and
cannot tell "undocumented" from "does not exist".

Nobody noticed because until recently `docs/man.q` DID NOT LOAD AT ALL - two
of its strings contained a bare `\\d` and `\\l`, and an invalid escape in a q
string literal makes q signal the whole string. It was not stale, it was
inert.

WHAT IS PRESERVED. Everything above the generated block: the table
definitions, the `register*` helpers, and the hand-written `.man.getDocs`,
`.man.getTS`, `.man.getOHLC` and `.man.getSymbols`. Those are infrastructure
and demo data, not derived from anything, so the generator rewrites only the
`register*` calls below them.

WHAT IS EMITTED. One `registerFile` per source file, then per documented
function a `registerFunc` plus one `registerArg` per `@param`, `@return`,
`@throws` and `@eg`. A function with no qDoc tags at all is skipped rather
than registered with an empty description - an entry that says nothing is
worse than an absence, because it makes the gap invisible to the very query
that should reveal it.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MAN = REPO / "docs" / "man.q"
SRC = REPO / "src"

#: Everything before this banner is hand-written and preserved verbatim.
#: Keying on a line number would break the moment anyone edits a helper above
#: it, so the cut is a marker in the text.
#:
#: The banner rather than the first `registerFile` call, because the banner is
#: itself part of the generated block. Cutting on the first call kept the
#: banner in the "prelude" and re-emitted it, so the file grew by seven lines
#: every run - a generator that is not idempotent makes `--check` fail
#: forever, and reports the file stale immediately after regenerating it.
GENERATED_BANNER = "/ GENERATED BY scripts/generate_man_registry.py"

#: The pre-generator file has no banner. Fall back to the first generated call
#: so the very first run can find the boundary; afterwards the banner is
#: always present.
LEGACY_MARKER = ".man.registerFile ("

#: A namespace declaration. Nested ones (`\d .qwrk.demo_deals_backfill`,
#: which is where every worker instance lives) are one namespace whose name
#: happens to contain a dot; the registry keys on the full name.
NS_RE = re.compile(r"^\\d\s+(\.[a-zA-Z][a-zA-Z0-9_]*(?:\.[a-zA-Z][a-zA-Z0-9_]*)*)\s*$")
#: A top-level definition. Deliberately NOT restricted to lambdas (`name:{`).
#: The hand-maintained file documented `.qstats.PI` (a constant), `.qdata.env`
#: (a dict) and `.qdata.pqm` (a value), and a generator that silently dropped
#: them would be losing documentation while reporting a threefold increase -
#: the worst possible trade, because the loss hides inside the gain.
#: Capitalised names are matched for the same reason: `PI` is not lowercase.
FUNC_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_]*)\s*:")

#: A FULLY-QUALIFIED top-level definition: `.qdag.register_pipelines:{`.
#: A file that uses this form instead of `\d` has no namespace declaration at
#: all, so without this it is invisible to the scan - silently, which is the
#: failure mode this repository keeps finding. `src/etl/generated/
#: pipeline_dag.q` is written that way on purpose.
QUALIFIED_RE = re.compile(r"^(\.[A-Za-z][A-Za-z0-9_]*)\.([A-Za-z][A-Za-z0-9_]*)\s*:")
#: A qDoc tag line.
TAG_RE = re.compile(r"^\s*/+\s*@(param|return|throws|eg)\b[ \t]*(.*)$")
#: A comment line that is not a tag.
COMMENT_RE = re.compile(r"^\s*/+[ \t]?(.*)$")


@dataclass
class Documented:
    """One function's qDoc block, flattened."""

    fullname: str
    namespace: str
    description: str = ""
    params: list[tuple[str, str]] = field(default_factory=list)
    returns: str = ""
    throws: list[str] = field(default_factory=list)
    examples: list[str] = field(default_factory=list)

    @property
    def documented(self) -> bool:
        """Has a structured tag, or a real prose description.

        Prose alone counts. The first version required a tag, which dropped
        five entries the hand-maintained file had - `.qstats.PI` and
        `.qdata.env` among them - because a constant has nothing to say about
        parameters or returns but its one-line description is still the whole
        of what a reader needs.

        What is still excluded is an entry with neither: registering a name
        with an empty description is worse than omitting it, because it makes
        the gap invisible to the very query meant to reveal it.
        """
        return bool(self.params or self.returns or self.examples or self.throws or self.description)


def q_escape(text: str) -> str:
    r"""Escape a Python string for a q string literal.

    Backslash first, or escaping the quotes would then double the backslashes
    this adds. And a bare `\d` in q string is not an escape at all - q signals
    the WHOLE STRING as the error, with no mention of escaping, which is the
    bug that made this file inert for its entire life.
    """
    return text.replace("\\", "\\\\").replace('"', '\\"')


def parse_file(path: Path) -> tuple[str, list[str], list[Documented]]:
    """(file title, namespaces, documented functions) for one source file."""
    lines = path.read_text(encoding="utf-8").splitlines()
    namespaces: list[str] = []
    out: list[Documented] = []
    current_ns = ""

    for i, line in enumerate(lines):
        ns_match = NS_RE.match(line)
        if ns_match:
            if ns_match.group(1) != ".":
                current_ns = ns_match.group(1)
                if current_ns not in namespaces:
                    namespaces.append(current_ns)
            continue

        qualified = QUALIFIED_RE.match(line)
        if qualified:
            ns_for_this, name = qualified.group(1), qualified.group(2)
            if ns_for_this not in namespaces:
                namespaces.append(ns_for_this)
        else:
            func_match = FUNC_RE.match(line)
            if not func_match or not current_ns:
                continue
            ns_for_this, name = current_ns, func_match.group(1)
        if name.startswith("_"):
            continue

        # Walk back over the contiguous comment block above the definition.
        #
        # A run of definitions with no blank line between them SHARES the one
        # block above the run. That is what the source actually means and
        # says: log.q's block opens "The four levels" and its own @eg names
        # `.qlog.info`, yet attaching the block only to the first definition
        # left `info` and `warn` reported as undocumented.
        #
        # Treating that as a documentation gap would have been the wrong
        # reading twice over: it invites writing near-identical docstrings
        # to satisfy a counter, when the source is already correct and the
        # parser was not.
        j = i - 1
        while j >= 0 and (FUNC_RE.match(lines[j]) or QUALIFIED_RE.match(lines[j])):
            j -= 1
        block: list[str] = []
        while j >= 0 and (lines[j].lstrip().startswith("/")) and lines[j].strip() != "\\":
            block.append(lines[j])
            j -= 1
        block.reverse()
        if not block:
            continue

        doc = Documented(fullname=f"{ns_for_this}.{name}", namespace=ns_for_this)
        prose: list[str] = []
        seen_tag = False
        for raw in block:
            tag = TAG_RE.match(raw)
            if tag:
                seen_tag = True
                kind, rest = tag.group(1), tag.group(2).strip()
                if kind == "param":
                    parts = rest.split(None, 1)
                    doc.params.append((parts[0], parts[1] if len(parts) > 1 else ""))
                elif kind == "return":
                    doc.returns = rest
                elif kind == "throws":
                    doc.throws.append(rest)
                else:
                    doc.examples.append(rest)
                continue
            if seen_tag:
                # A continuation line under a tag, or a trailing note. Append
                # to whichever tag it follows rather than to the description,
                # which would put argument prose in the summary.
                text = COMMENT_RE.match(raw)
                body = text.group(1).strip() if text else ""
                if body and body != "." and doc.examples:
                    doc.examples[-1] = f"{doc.examples[-1]} {body}".strip()
                continue
            text = COMMENT_RE.match(raw)
            body = text.group(1).strip() if text else ""
            # `/ .` is this repository's blank-line-inside-a-comment idiom,
            # written that way because a line containing only `/` opens a
            # multi-line comment block and silently comments out the file.
            prose.append("" if body == "." else body)

        doc.description = " ".join(p for p in prose if p).strip()
        if doc.documented:
            out.append(doc)

    title = path.name
    return title, namespaces, out


def file_header(path: Path) -> str:
    """The file's own leading comment, as its registerFile description."""
    lines = path.read_text(encoding="utf-8").splitlines()
    prose: list[str] = []
    for raw in lines:
        if not raw.lstrip().startswith("/"):
            break
        text = COMMENT_RE.match(raw)
        body = text.group(1).strip() if text else ""
        prose.append("" if body == "." else body)
    return " ".join(p for p in prose if p).strip()


def render_entries() -> list[str]:
    """Every `register*` call, in stable source order."""
    lines: list[str] = []
    for path in sorted(SRC.rglob("*.q")):
        title, namespaces, docs = parse_file(path)
        if not docs:
            continue
        header = file_header(path)
        lines.append(
            f'.man.registerFile ("{q_escape(title)}";"";'
            f'"{q_escape("|".join(namespaces))}";"{q_escape(header)}");'
        )
        for doc in docs:
            example = doc.examples[0] if doc.examples else ""
            lines.append(
                f'.man.registerFunc ("{q_escape(doc.fullname)}";'
                f'"{q_escape(doc.namespace)}";'
                f'"{q_escape(doc.description)}";'
                f'"{q_escape(doc.fullname)}";'
                f'"{q_escape(example)}");'
            )
            for pname, pdesc in doc.params:
                lines.append(
                    f'.man.registerArg ("{q_escape(doc.fullname)}";"param";'
                    f'"{q_escape(pname)}";"{q_escape(pdesc)}");'
                )
            if doc.returns:
                lines.append(
                    f'.man.registerArg ("{q_escape(doc.fullname)}";"return";"";'
                    f'"{q_escape(doc.returns)}");'
                )
            for thr in doc.throws:
                lines.append(
                    f'.man.registerArg ("{q_escape(doc.fullname)}";"throws";"";"{q_escape(thr)}");'
                )
            for eg in doc.examples:
                lines.append(
                    f'.man.registerArg ("{q_escape(doc.fullname)}";"eg";"";"{q_escape(eg)}");'
                )
        lines.append("")
    return lines


def render() -> str:
    """The whole file: preserved prelude plus regenerated entries."""
    existing = MAN.read_text(encoding="utf-8").splitlines()
    cut = next(
        (i for i, line in enumerate(existing) if line.startswith(GENERATED_BANNER)),
        None,
    )
    if cut is not None:
        # Step back over the rule line that opens the banner block.
        while cut > 0 and existing[cut - 1].startswith("/ ---"):
            cut -= 1
    else:
        cut = next(
            (i for i, line in enumerate(existing) if line.startswith(LEGACY_MARKER)),
            None,
        )
    if cut is None:
        raise SystemExit(
            f"found neither the generated banner nor {LEGACY_MARKER!r} in "
            f"{MAN.relative_to(REPO)} - refusing to guess where the hand-written "
            "prelude ends"
        )
    prelude = existing[:cut]
    while prelude and not prelude[-1].strip():
        prelude.pop()
    body = [
        "",
        "/ ---------------------------------------------------------------------",
        GENERATED_BANNER + " - DO NOT EDIT BELOW HERE.",
        "/ .",
        "/ Derived from the qDoc comments in src/**/*.q. Edit the source comment,",
        "/ then rerun the generator; CI checks that they agree.",
        "/ ---------------------------------------------------------------------",
        "",
    ]
    return "\n".join(prelude + body + render_entries()).rstrip("\n") + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="diff against the committed file")
    args = ap.parse_args()

    generated = render()
    if not args.check:
        MAN.write_text(generated, encoding="utf-8")
        funcs = generated.count(".man.registerFunc (")
        print(f"wrote {MAN.relative_to(REPO)}: {funcs} function(s) registered")
        return 0

    committed = MAN.read_text(encoding="utf-8")
    if committed == generated:
        print(f"{MAN.relative_to(REPO)} matches the qDoc comments in src/")
        return 0
    print(f"{MAN.relative_to(REPO)} is stale - rerun the generator:", file=sys.stderr)
    sys.stderr.writelines(
        difflib.unified_diff(
            committed.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile="committed",
            tofile="generated",
            n=1,
        )
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
