// Generated qdoc tables to allow programmatic use of documentation.
.man.funcs:([] fullname:(); ns:(); description:(); name:(); other:());
.man.registerFunc:{`.man.funcs insert `fullname`ns`description`name`other!(),/:x};
.man.args:([] fullname:(); tag:(); param:(); description:());
.man.registerArg:{`.man.args insert `fullname`tag`param`description!(),/:x};
.man.files:([] title:(); author:(); namespaces:(); header:());
.man.registerFile:{`.man.files insert `title`author`namespaces`header!(),/:x};
.man.filetags:([] title:(); tag:(); val:());
.man.registerFileTag:{`.man.filetags insert `title`tag`val!(),/:x};

/ @eg .man.getDocs[]
/ @return table of format ([] fullname; tag; param; description)
.man.getDocs:{[]
    ft:select fullname,description from .man.funcs;
    at:select fullname,tag,param,description from .man.args;
    headerTbl:0!select description:"\n" sv header by title,fullname:{first "|" vs x} each namespaces from .man.files where 1<count each trim namespaces,1<count each trim header;
    filenameToNSDict:exec first fullname by title from headerTbl;
    tagTbl:select fullname:filenameToNSDict title, tag,description:val from .man.filetags;
    t:at uj ft uj tagTbl uj (``title _ headerTbl);
    t:asc select from t where (0<count each tag) or (0<count each param) or (0<count each description);
    t };



/ @eg .man.getTS[`GOOG]
.man.getTS:{[symbol]  // random walk with set seed to mimic incoming data
    seed:prd `int$string symbol;
    {  walk:{ [seed;n]
    	 r:{{ abs ((1664525*x)+1013904223) mod 4294967296}\[y-1;x]};
    	 prds (100+((r[seed;n]) mod 11)-5)%100};
    	 c:{x mod `long$00:20:00.0t}x;   st:x-c;   cn:`long$c%1000;
    	 ([] time:.z.d+st+1000*til cn; gold:walk[y;cn])  }[.z.t;seed]
    };

/ @eg .man.getOHLC[`MSFT]
.man.getOHLC:{[symbol]
    seed:prd `int$string symbol;
    {  r:{{ abs ((1664525*x)+1013904223) mod 4294967296}\[y-1;x]};
	walk:{ [r;seed;n] prds (100+((r[seed;n]) mod 11)-5)%100}[r;;];
	c:{x mod `long$00:05:00.0t}x;   st:x-c;   cn:100+`long$c%1000;
	t:([] time:`second$.z.d+st+1000*til cn; open:walk[y+4;cn]; close:walk[y+3;cn]);
	-100 sublist update low:?[open > close;close;open]-(r[11;cn] mod 11)*0.02,high:?[open < close;close;open]+(r[44;cn] mod 11)*0.02,volume:(r[44;cn] mod 110) from t}[.z.t;seed]
    };

/ @eg .man.getSymbols[]
.man.getSymbols:{[]
    sym:`MSFT`AAPL`NVDA`AMZN`GOOGL`META`BRK.B`AVGO`TSLA`TSM`WMT`JPM`V`LLY`MA`NFLX`XOM`COST`ORCL`JNJ`PG`HD`UNH`SAP`ABBV`BAC`KO`NVO;
    des:("Microsoft Corporation";"Apple Inc.";"NVIDIA Corporation";"Amazon.com, Inc.";"Alphabet Inc.";"Meta Platforms, Inc.";"Berkshire Hathaway Inc.";"Broadcom Inc.";"Tesla, Inc.";"Taiwan Semiconductor Manufacturing Company Limited";"Walmart Inc.";"JPMorgan Chase & Co.";"Visa Inc.";"Eli Lilly and Company";"Mastercard Incorporated";"Netflix, Inc.";"Exxon Mobil Corporation";"Costco Wholesale Corporation";"Oracle Corporation";"Johnson & Johnson";"The Procter & Gamble Company";"The Home Depot, Inc.";"UnitedHealth Group Incorporated";"SAP SE";"AbbVie Inc.";"Bank of America Corporation";"The Coca-Cola Company";"Novo Nordisk A/S");
    t:update query:(`$".man.getTS[`XXX]") from ([] symbol:sym; title:`$des);
    t,:select query:(`$".man.getOHLC[`XXX]"),symbol:(`$string[symbol],\:"_OHLC"),title from t;
    t};


.man.registerFile ("ccy.q";"";".qccy";"ccy.q - currency pair symbol conventions: canonical CURCUR validation and normalization from looser input formats (lowercase, with separators). . Canonical form used throughout this library is CURCUR - six uppercase letters, no separator, e.g. `EURUSD (not `eurusd, not \"EUR/USD\").");
.man.registerFunc (".qccy.ccy_pair_legs";".qccy";"Split a currency pair (any reasonable format - normalized first) into its base and quote 3-letter currency codes.";".qccy.ccy_pair_legs";".qccy.ccy_pair_legs `EURUSD  -> `base`quote!(`EUR;`USD)");
.man.registerArg (".qccy.ccy_pair_legs";"param";"pair";"a symbol or string, e.g. `EURUSD, \"eur/usd\"");
.man.registerArg (".qccy.ccy_pair_legs";"eg";"";".qccy.ccy_pair_legs `EURUSD  -> `base`quote!(`EUR;`USD)");
.man.registerArg (".qccy.ccy_pair_legs";"throws";"";"error if pair cannot be normalized to a 6-letter CURCUR pair");
.man.registerArg (".qccy.ccy_pair_legs";"return";"";"dict `base`quote!(baseSym;quoteSym)");
.man.registerFunc (".qccy.ccy_pair_symbol";".qccy";"Build a canonical CURCUR pair symbol from a 3-letter base and quote currency code.";".qccy.ccy_pair_symbol";".qccy.ccy_pair_symbol[`EUR;`USD]  -> `EURUSD");
.man.registerArg (".qccy.ccy_pair_symbol";"param";"quote";"3-letter quote currency code, e.g. `USD or \"usd\"");
.man.registerArg (".qccy.ccy_pair_symbol";"param";"base";"3-letter base currency code, e.g. `EUR or \"eur\"");
.man.registerArg (".qccy.ccy_pair_symbol";"eg";"";".qccy.ccy_pair_symbol[`EUR;`USD]  -> `EURUSD");
.man.registerArg (".qccy.ccy_pair_symbol";"throws";"";"error if base or quote is not a 3-letter alphabetic code");
.man.registerArg (".qccy.ccy_pair_symbol";"return";"";"the canonical CURCUR symbol, e.g. `EURUSD");
.man.registerFunc (".qccy.ccy_to_str";".qccy";"Private: string-coerce x without exploding an already-string input into a list of 1-char strings - `string` on a char vector maps over each char instead of acting as the identity, which is a real q gotcha.";".qccy.ccy_to_str";".qccy.ccy_to_str `EURUSD  -> \"EURUSD\"");
.man.registerArg (".qccy.ccy_to_str";"param";"x";"a symbol or string");
.man.registerArg (".qccy.ccy_to_str";"eg";"";".qccy.ccy_to_str `EURUSD  -> \"EURUSD\"");
.man.registerArg (".qccy.ccy_to_str";"return";"";"x as a plain string");
.man.registerFunc (".qccy.is_ccy_pair";".qccy";"True if x is already in canonical CURCUR form: exactly 6 uppercase letters, no separator.";".qccy.is_ccy_pair";"");
.man.registerArg (".qccy.is_ccy_pair";"eg";".qccy.is_ccy_pair";"\"eur/usd\"  -> 0b");
.man.registerArg (".qccy.is_ccy_pair";"param";"x";"a symbol or string");
.man.registerArg (".qccy.is_ccy_pair";"return";"";"1b if x is a valid CURCUR pair, else 0b");
.man.registerFunc (".qccy.normalize_ccy_pair";".qccy";"Normalize a currency pair into canonical CURCUR form: uppercases and strips common separators (/, -, _, space).";".qccy.normalize_ccy_pair";".qccy.normalize_ccy_pair \"eur/usd\"  -> `EURUSD");
.man.registerArg (".qccy.normalize_ccy_pair";"param";"x";"a symbol or string, e.g. `eurusd, \"EUR/USD\", \"eur-usd\"");
.man.registerArg (".qccy.normalize_ccy_pair";"eg";"";".qccy.normalize_ccy_pair \"eur/usd\"  -> `EURUSD");
.man.registerArg (".qccy.normalize_ccy_pair";"throws";"";"error if x cannot be normalized to a 6-letter CURCUR pair");
.man.registerArg (".qccy.normalize_ccy_pair";"return";"";"the canonical CURCUR symbol, e.g. `EURUSD");
.man.registerFile ("init.q";"";"";"init.q - loads every uqf module, each into its own flat namespace (one per file - .qstats, .qccy, .qdcf, .qrates, .qfwd, .qopt, .qrisk, .qexec, .qbook, .qmicro, .qex - kept single-level throughout, not nested under a shared .q parent, since multi-level \d namespace paths don't resolve under the PeachQ interpreter this repo also targets). Run from the repository root, e.g. `q src/init.q` or `\l src/init.q`.");
.man.registerFile ("execution.q";"";".qexec";"execution.q - eFX execution-quality analytics: markouts, effective spread, slippage and quoting/fill statistics. . Sign convention used throughout: side is 1 for a client/algo buy (long base currency) and -1 for a sell. Every *cost* style metric (eff_spread, slippage) is positive when it went against the side taking the trade; markout is positive when the market moved in that side's favour after the trade (i.e. positive markout received by a client is \"toxic flow\" from a liquidity provider's point of view - flip side to view it from the LP's side of the same trade).");
.man.registerFunc (".qexec.eff_spread";".qexec";"Effective spread paid/received relative to the prevailing mid at the moment of execution, in pips. Positive = cost to the side that traded.";".qexec.eff_spread";".qexec.eff_spread[1;1.1002;1.1000;10000]  -> 4f");
.man.registerArg (".qexec.eff_spread";"param";"mid_at_trade";"the mid price at the moment of execution");
.man.registerArg (".qexec.eff_spread";"param";"side";"1 for a buy, -1 for a sell");
.man.registerArg (".qexec.eff_spread";"param";"trade_price";"the execution price");
.man.registerArg (".qexec.eff_spread";"param";"pip_factor";"10000 for most pairs, 100 for JPY crosses");
.man.registerArg (".qexec.eff_spread";"eg";"";".qexec.eff_spread[1;1.1002;1.1000;10000]  -> 4f");
.man.registerArg (".qexec.eff_spread";"return";"";"the effective spread, in pips");
.man.registerFunc (".qexec.fill_ratio";".qexec";"Fraction of quotes/orders that resulted in a fill.";".qexec.fill_ratio";".qexec.fill_ratio[73;100]  -> 0.73");
.man.registerArg (".qexec.fill_ratio";"param";"num_fills";"number of filled orders");
.man.registerArg (".qexec.fill_ratio";"param";"num_quotes";"number of quotes/orders sent");
.man.registerArg (".qexec.fill_ratio";"eg";"";".qexec.fill_ratio[73;100]  -> 0.73");
.man.registerArg (".qexec.fill_ratio";"return";"";"the fill ratio, in [0,1]");
.man.registerFunc (".qexec.markout";".qexec";"Post-trade price movement: how far the reference/mid price has moved, in pips, from the trade price by the time ref_price was observed. ref_price may be a single price or a vector of prices at several horizons (t+1s, t+10s, t+60s, ...) - the function vectorises naturally.";".qexec.markout";".qexec.markout[1;1.1000;1.1010;10000]  -> 10f");
.man.registerArg (".qexec.markout";"param";"side";"1 for a buy, -1 for a sell");
.man.registerArg (".qexec.markout";"param";"trade_price";"the execution price");
.man.registerArg (".qexec.markout";"param";"ref_price";"the reference/mid price at the markout horizon (atom or vector)");
.man.registerArg (".qexec.markout";"param";"pip_factor";"10000 for most pairs, 100 for JPY crosses");
.man.registerArg (".qexec.markout";"eg";"";".qexec.markout[1;1.1000;1.1010;10000]  -> 10f");
.man.registerArg (".qexec.markout";"return";"";"the markout, in pips");
.man.registerFunc (".qexec.markout_at_horizons";".qexec";"Markout at one or more time horizons after each trade, looking up the reference mid itself via an as-of join against a quote table - the table-native companion to markout, for when you have trades and quotes as tables rather than an already-aligned ref_price vector. For each trade and each horizon, finds the most recent quote at or before trade_time+horizon (same semantics as kdb+'s aj) and computes markout against its mid. A trade/horizon pair with no quote at or before the target time gets a null ref_price and a null markout_pips - filter with `where not null markout_pips` if you want to drop those rather than see them.";".qexec.markout_at_horizons";".qexec.markout_at_horizons[trades;quotes;0D00:00:01 0D00:00:10]");
.man.registerArg (".qexec.markout_at_horizons";"param";"trades";"table with columns `sym`time`side`trade_price`pip_factor");
.man.registerArg (".qexec.markout_at_horizons";"param";"quotes";"table with columns `sym`time`mid - need not be pre-sorted, this sorts its own copy before joining");
.man.registerArg (".qexec.markout_at_horizons";"param";"horizons";"a timespan, or list of timespans, to look ahead from each trade's time, e.g. 0D00:00:01 0D00:00:10 0D00:01:00 for 1s/10s/1m");
.man.registerArg (".qexec.markout_at_horizons";"eg";"";".qexec.markout_at_horizons[trades;quotes;0D00:00:01 0D00:00:10]");
.man.registerArg (".qexec.markout_at_horizons";"return";"";"a table with one row per (trade, horizon): `sym`trade_time`horizon`target_time`trade_price`ref_price`markout_pips");
.man.registerFunc (".qexec.reject_ratio";".qexec";"Fraction of trade requests rejected (e.g. under last look).";".qexec.reject_ratio";".qexec.reject_ratio[4;100]  -> 0.04");
.man.registerArg (".qexec.reject_ratio";"param";"num_rejects";"number of rejected requests");
.man.registerArg (".qexec.reject_ratio";"param";"num_requests";"total number of requests");
.man.registerArg (".qexec.reject_ratio";"eg";"";".qexec.reject_ratio[4;100]  -> 0.04");
.man.registerArg (".qexec.reject_ratio";"return";"";"the reject ratio, in [0,1]");
.man.registerFunc (".qexec.slippage";".qexec";"Slippage between a decision/arrival price and the actual execution price, in pips. Positive = cost to the side that traded.";".qexec.slippage";".qexec.slippage[1;1.1000;1.1003;10000]  -> 3f");
.man.registerArg (".qexec.slippage";"param";"arrival_price";"the decision/arrival price");
.man.registerArg (".qexec.slippage";"param";"side";"1 for a buy, -1 for a sell");
.man.registerArg (".qexec.slippage";"param";"exec_price";"the actual execution price");
.man.registerArg (".qexec.slippage";"param";"pip_factor";"10000 for most pairs, 100 for JPY crosses");
.man.registerArg (".qexec.slippage";"eg";"";".qexec.slippage[1;1.1000;1.1003;10000]  -> 3f");
.man.registerArg (".qexec.slippage";"return";"";"the slippage, in pips");
.man.registerFunc (".qexec.sweep_price";".qexec";"Walk a stack of order book levels to price a sweep of target_size: the blended price you'd get consuming best-to-worst levels until target_size is filled or the book runs out. Pass the ask side (best/lowest price first) to price a buy/sweep-the-offer, or the bid side (best/highest price first) to price a sell/sweep-the-bid - this function doesn't care which side it is, only that prices/sizes are already ordered best-first.";".qexec.sweep_price";".qexec.sweep_price[1.1000 1.1002 1.1005;1000000 1000000 2000000;3000000]  -> `avg_price`worst_price`filled_size`fully_filled!(1.100233;1.1005;3000000;1b)");
.man.registerArg (".qexec.sweep_price";"param";"target_size";"the size you want to sweep");
.man.registerArg (".qexec.sweep_price";"param";"sizes";"level sizes, same length as prices, aligned to the same levels");
.man.registerArg (".qexec.sweep_price";"param";"prices";"level prices, best (most aggressive) first");
.man.registerArg (".qexec.sweep_price";"eg";"";".qexec.sweep_price[1.1000 1.1002 1.1005;1000000 1000000 2000000;3000000]  -> `avg_price`worst_price`filled_size`fully_filled!(1.100233;1.1005;3000000;1b)");
.man.registerArg (".qexec.sweep_price";"throws";"";"error if target_size is not positive, or prices/sizes differ in length");
.man.registerArg (".qexec.sweep_price";"return";"";"dict `avg_price`worst_price`filled_size`fully_filled - avg_price is the size-weighted blended execution price (null if nothing filled), worst_price is the price of the last level touched (the marginal fill, null if nothing filled), filled_size is how much actually filled (may be less than target_size if the book doesn't have enough depth), and fully_filled is 1b iff filled_size>=target_size");
.man.registerFunc (".qexec.vwap";".qexec";"Size-weighted average execution price across a set of fills.";".qexec.vwap";".qexec.vwap[1.1000 1.1010 1.1005;1000000 2000000 1000000]  -> 1.100625");
.man.registerArg (".qexec.vwap";"param";"sizes";"list of fill sizes, same length as prices");
.man.registerArg (".qexec.vwap";"param";"prices";"list of fill prices");
.man.registerArg (".qexec.vwap";"eg";"";".qexec.vwap[1.1000 1.1010 1.1005;1000000 2000000 1000000]  -> 1.100625");
.man.registerArg (".qexec.vwap";"return";"";"the size-weighted average price");
.man.registerFile ("rates.q";"";".qrates";"rates.q - discount/growth factors and compounding conversions. t is a year fraction (see daycount.q), r a decimal annual rate (0.05 = 5%). .");
.man.registerFunc (".qrates.cont_to_simple";".qrates";"Convert a continuously compounded rate to the equivalent simple rate over the same period t.";".qrates.cont_to_simple";".qrates.cont_to_simple[0.04879016;1]  -> 0.05");
.man.registerArg (".qrates.cont_to_simple";"param";"r";"continuously compounded decimal annual rate");
.man.registerArg (".qrates.cont_to_simple";"param";"t";"year fraction");
.man.registerArg (".qrates.cont_to_simple";"eg";"";".qrates.cont_to_simple[0.04879016;1]  -> 0.05");
.man.registerArg (".qrates.cont_to_simple";"return";"";"the simple rate with the same growth over t");
.man.registerFunc (".qrates.df_cont";".qrates";"Continuous-compounding discount factor.";".qrates.df_cont";".qrates.df_cont[0.05;1]  -> 0.9512294");
.man.registerArg (".qrates.df_cont";"param";"r";"decimal annual rate");
.man.registerArg (".qrates.df_cont";"param";"t";"year fraction");
.man.registerArg (".qrates.df_cont";"eg";"";".qrates.df_cont[0.05;1]  -> 0.9512294");
.man.registerArg (".qrates.df_cont";"return";"";"exp(-r*t)");
.man.registerFunc (".qrates.df_simple";".qrates";"Simple-compounding discount factor.";".qrates.df_simple";".qrates.df_simple[0.05;1]  -> 0.952381");
.man.registerArg (".qrates.df_simple";"param";"r";"decimal annual rate");
.man.registerArg (".qrates.df_simple";"param";"t";"year fraction");
.man.registerArg (".qrates.df_simple";"eg";"";".qrates.df_simple[0.05;1]  -> 0.952381");
.man.registerArg (".qrates.df_simple";"return";"";"1/(1+r*t)");
.man.registerFunc (".qrates.growth_cont";".qrates";"Continuous-compounding growth factor.";".qrates.growth_cont";".qrates.growth_cont[0.05;1]  -> 1.051271");
.man.registerArg (".qrates.growth_cont";"param";"r";"decimal annual rate");
.man.registerArg (".qrates.growth_cont";"param";"t";"year fraction");
.man.registerArg (".qrates.growth_cont";"eg";"";".qrates.growth_cont[0.05;1]  -> 1.051271");
.man.registerArg (".qrates.growth_cont";"return";"";"exp(r*t)");
.man.registerFunc (".qrates.growth_simple";".qrates";"Simple-compounding growth factor.";".qrates.growth_simple";".qrates.growth_simple[0.05;1]  -> 1.05");
.man.registerArg (".qrates.growth_simple";"param";"r";"decimal annual rate");
.man.registerArg (".qrates.growth_simple";"param";"t";"year fraction");
.man.registerArg (".qrates.growth_simple";"eg";"";".qrates.growth_simple[0.05;1]  -> 1.05");
.man.registerArg (".qrates.growth_simple";"return";"";"1+r*t");
.man.registerFunc (".qrates.simple_to_cont";".qrates";"Convert a simple-compounded rate to the equivalent continuously compounded rate over the same period t.";".qrates.simple_to_cont";".qrates.simple_to_cont[0.05;1]  -> 0.04879016");
.man.registerArg (".qrates.simple_to_cont";"param";"r";"simple decimal annual rate");
.man.registerArg (".qrates.simple_to_cont";"param";"t";"year fraction");
.man.registerArg (".qrates.simple_to_cont";"eg";"";".qrates.simple_to_cont[0.05;1]  -> 0.04879016");
.man.registerArg (".qrates.simple_to_cont";"return";"";"the continuously compounded rate with the same growth over t");
.man.registerFile ("options.q";"";".qopt";"options.q - Garman-Kohlhagen pricing for European FX vanilla options. . s = spot, k = strike, rd = domestic (quote-currency) risk-free rate, rf = foreign (base-currency) risk-free rate, sigma = volatility (decimal, e.g. 0.10 = 10%), t = year fraction to expiry. Setting rf=0 reduces the model to plain Black-Scholes. . Requires stats.q (ncdf/npdf) and rates.q (df_cont) to be loaded first.");
.man.registerFunc (".qopt.bisect_vol";".qopt";"Private: bisection search used as a robust fallback for implied_vol when Newton-Raphson stalls (vega ~ 0). gk_price is monotone increasing in sigma, so bisection over a wide bracket always converges.";".qopt.bisect_vol";".qopt.bisect_vol[0.03781082;1.10;1.12;0.045;0.02;0.75;1b]  -> 0.1 (approx)");
.man.registerArg (".qopt.bisect_vol";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.bisect_vol";"param";"s";"spot rate");
.man.registerArg (".qopt.bisect_vol";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.bisect_vol";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.bisect_vol";"param";"price";"observed option premium");
.man.registerArg (".qopt.bisect_vol";"param";"is_call";"1b for a call, 0b for a put");
.man.registerArg (".qopt.bisect_vol";"param";"k";"strike");
.man.registerArg (".qopt.bisect_vol";"eg";"";".qopt.bisect_vol[0.03781082;1.10;1.12;0.045;0.02;0.75;1b]  -> 0.1 (approx)");
.man.registerArg (".qopt.bisect_vol";"return";"";"sigma such that gk_price[...;sigma;...;is_call] ~ price");
.man.registerFunc (".qopt.d1";".qopt";"The Garman-Kohlhagen d1 term.";".qopt.d1";".qopt.d1[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.05174784");
.man.registerArg (".qopt.d1";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.d1";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.d1";"param";"s";"spot rate");
.man.registerArg (".qopt.d1";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.d1";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.d1";"param";"k";"strike");
.man.registerArg (".qopt.d1";"eg";"";".qopt.d1[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.05174784");
.man.registerArg (".qopt.d1";"return";"";"the Garman-Kohlhagen d1 term");
.man.registerFunc (".qopt.d1_d2";".qopt";"Private: (d1;d2) computed together so callers never duplicate the underlying arithmetic (see src/stats.q for why that matters in q).";".qopt.d1_d2";".qopt.d1_d2[1.10;1.12;0.045;0.02;0.10;0.75]  -> (0.05174784;-0.0348547)");
.man.registerArg (".qopt.d1_d2";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.d1_d2";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.d1_d2";"param";"s";"spot rate");
.man.registerArg (".qopt.d1_d2";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.d1_d2";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.d1_d2";"param";"k";"strike");
.man.registerArg (".qopt.d1_d2";"eg";"";".qopt.d1_d2[1.10;1.12;0.045;0.02;0.10;0.75]  -> (0.05174784;-0.0348547)");
.man.registerArg (".qopt.d1_d2";"return";"";"(d1;d2)");
.man.registerFunc (".qopt.d2";".qopt";"The Garman-Kohlhagen d2 term.";".qopt.d2";".qopt.d2[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.0348547");
.man.registerArg (".qopt.d2";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.d2";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.d2";"param";"s";"spot rate");
.man.registerArg (".qopt.d2";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.d2";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.d2";"param";"k";"strike");
.man.registerArg (".qopt.d2";"eg";"";".qopt.d2[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.0348547");
.man.registerArg (".qopt.d2";"return";"";"the Garman-Kohlhagen d2 term");
.man.registerFunc (".qopt.gk_call";".qopt";"European call premium, in domestic/quote currency per unit of base notional.";".qopt.gk_call";".qopt.gk_call[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.03781082");
.man.registerArg (".qopt.gk_call";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_call";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_call";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_call";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_call";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_call";"param";"k";"strike");
.man.registerArg (".qopt.gk_call";"eg";"";".qopt.gk_call[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.03781082");
.man.registerArg (".qopt.gk_call";"return";"";"the call premium");
.man.registerFunc (".qopt.gk_delta_call";".qopt";"Call delta: sensitivity of the premium to a change in spot.";".qopt.gk_delta_call";".qopt.gk_delta_call[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.512884");
.man.registerArg (".qopt.gk_delta_call";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_delta_call";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_delta_call";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_delta_call";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_delta_call";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_delta_call";"param";"k";"strike");
.man.registerArg (".qopt.gk_delta_call";"eg";"";".qopt.gk_delta_call[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.512884");
.man.registerArg (".qopt.gk_delta_call";"return";"";"the call delta, in (0, exp(-rf*t))");
.man.registerFunc (".qopt.gk_delta_put";".qopt";"Put delta: sensitivity of the premium to a change in spot.";".qopt.gk_delta_put";".qopt.gk_delta_put[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.4722279");
.man.registerArg (".qopt.gk_delta_put";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_delta_put";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_delta_put";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_delta_put";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_delta_put";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_delta_put";"param";"k";"strike");
.man.registerArg (".qopt.gk_delta_put";"eg";"";".qopt.gk_delta_put[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.4722279");
.man.registerArg (".qopt.gk_delta_put";"return";"";"the put delta, in (-exp(-rf*t), 0)");
.man.registerFunc (".qopt.gk_gamma";".qopt";"Gamma: sensitivity of delta to a change in spot. Identical for call and put.";".qopt.gk_gamma";".qopt.gk_gamma[1.10;1.12;0.045;0.02;0.10;0.75]  -> 4.11994");
.man.registerArg (".qopt.gk_gamma";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_gamma";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_gamma";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_gamma";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_gamma";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_gamma";"param";"k";"strike");
.man.registerArg (".qopt.gk_gamma";"eg";"";".qopt.gk_gamma[1.10;1.12;0.045;0.02;0.10;0.75]  -> 4.11994");
.man.registerArg (".qopt.gk_gamma";"return";"";"gamma (always positive)");
.man.registerFunc (".qopt.gk_price";".qopt";"Private: dispatch to gk_call/gk_put by an is_call boolean.";".qopt.gk_price";".qopt.gk_price[1.10;1.12;0.045;0.02;0.10;0.75;1b]  -> 0.03781082");
.man.registerArg (".qopt.gk_price";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_price";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_price";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_price";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_price";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_price";"param";"is_call";"1b for a call, 0b for a put");
.man.registerArg (".qopt.gk_price";"param";"k";"strike");
.man.registerArg (".qopt.gk_price";"eg";"";".qopt.gk_price[1.10;1.12;0.045;0.02;0.10;0.75;1b]  -> 0.03781082");
.man.registerArg (".qopt.gk_price";"return";"";"the call or put premium");
.man.registerFunc (".qopt.gk_put";".qopt";"European put premium, in domestic/quote currency per unit of base notional.";".qopt.gk_put";".qopt.gk_put[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.03701845");
.man.registerArg (".qopt.gk_put";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_put";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_put";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_put";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_put";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_put";"param";"k";"strike");
.man.registerArg (".qopt.gk_put";"eg";"";".qopt.gk_put[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.03701845");
.man.registerArg (".qopt.gk_put";"return";"";"the put premium");
.man.registerFunc (".qopt.gk_rho_call";".qopt";"Call rho: sensitivity to the domestic rate rd.";".qopt.gk_rho_call";".qopt.gk_rho_call[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.3947712");
.man.registerArg (".qopt.gk_rho_call";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_rho_call";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_rho_call";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_rho_call";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_rho_call";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_rho_call";"param";"k";"strike");
.man.registerArg (".qopt.gk_rho_call";"eg";"";".qopt.gk_rho_call[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.3947712");
.man.registerArg (".qopt.gk_rho_call";"return";"";"the call's rho");
.man.registerFunc (".qopt.gk_rho_put";".qopt";"Put rho: sensitivity to the domestic rate rd.";".qopt.gk_rho_put";".qopt.gk_rho_put[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.4173519");
.man.registerArg (".qopt.gk_rho_put";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_rho_put";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_rho_put";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_rho_put";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_rho_put";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_rho_put";"param";"k";"strike");
.man.registerArg (".qopt.gk_rho_put";"eg";"";".qopt.gk_rho_put[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.4173519");
.man.registerArg (".qopt.gk_rho_put";"return";"";"the put's rho");
.man.registerFunc (".qopt.gk_theta_call";".qopt";"Call theta: time decay per year (-dV/dT); divide by 365 for a per-calendar-day figure.";".qopt.gk_theta_call";".qopt.gk_theta_call[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.03732846");
.man.registerArg (".qopt.gk_theta_call";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_theta_call";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_theta_call";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_theta_call";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_theta_call";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_theta_call";"param";"k";"strike");
.man.registerArg (".qopt.gk_theta_call";"eg";"";".qopt.gk_theta_call[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.03732846");
.man.registerArg (".qopt.gk_theta_call";"return";"";"the call's theta");
.man.registerFunc (".qopt.gk_theta_put";".qopt";"Put theta: time decay per year (-dV/dT); divide by 365 for a per-calendar-day figure.";".qopt.gk_theta_put";".qopt.gk_theta_put[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.01027354");
.man.registerArg (".qopt.gk_theta_put";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_theta_put";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_theta_put";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_theta_put";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_theta_put";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_theta_put";"param";"k";"strike");
.man.registerArg (".qopt.gk_theta_put";"eg";"";".qopt.gk_theta_put[1.10;1.12;0.045;0.02;0.10;0.75]  -> -0.01027354");
.man.registerArg (".qopt.gk_theta_put";"return";"";"the put's theta");
.man.registerFunc (".qopt.gk_vega";".qopt";"Vega: sensitivity of the premium to a 1.00 (100%) change in vol. Identical for call and put; divide by 100 for the usual \"per vol point\" desk convention.";".qopt.gk_vega";".qopt.gk_vega[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.3738845");
.man.registerArg (".qopt.gk_vega";"param";"sigma";"volatility, decimal (0.10 = 10%)");
.man.registerArg (".qopt.gk_vega";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.gk_vega";"param";"s";"spot rate");
.man.registerArg (".qopt.gk_vega";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.gk_vega";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.gk_vega";"param";"k";"strike");
.man.registerArg (".qopt.gk_vega";"eg";"";".qopt.gk_vega[1.10;1.12;0.045;0.02;0.10;0.75]  -> 0.3738845");
.man.registerArg (".qopt.gk_vega";"return";"";"vega (always positive)");
.man.registerFunc (".qopt.implied_vol";".qopt";"Implied volatility via Newton-Raphson (vega as derivative), falling back to bisection if vega collapses.";".qopt.implied_vol";".qopt.implied_vol[.qopt.gk_call[1.10;1.12;0.045;0.02;0.12;0.75];1.10;1.12;0.045;0.02;0.75;1b]  -> 0.12");
.man.registerArg (".qopt.implied_vol";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qopt.implied_vol";"param";"s";"spot rate");
.man.registerArg (".qopt.implied_vol";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qopt.implied_vol";"param";"t";"year fraction to expiry");
.man.registerArg (".qopt.implied_vol";"param";"price";"observed option premium");
.man.registerArg (".qopt.implied_vol";"param";"is_call";"1b for a call, 0b for a put");
.man.registerArg (".qopt.implied_vol";"param";"k";"strike");
.man.registerArg (".qopt.implied_vol";"eg";"";".qopt.implied_vol[.qopt.gk_call[1.10;1.12;0.045;0.02;0.12;0.75];1.10;1.12;0.045;0.02;0.75;1b]  -> 0.12");
.man.registerArg (".qopt.implied_vol";"return";"";"sigma such that gk_price[...;sigma;...;is_call] ~ price");
.man.registerFile ("risk.q";"";".qrisk";"risk.q - position-level P&L, carry and Value-at-Risk helpers for an FX book. Requires stats.q (inv_ncdf) to be loaded first for var_parametric. .");
.man.registerFunc (".qrisk.carry_pnl";".qrisk";"Money value of that same forward premium/discount on a given notional.";".qrisk.carry_pnl";".qrisk.carry_pnl[1000000;1.10;1.1050]  -> 5000f");
.man.registerArg (".qrisk.carry_pnl";"param";"notional";"position size in base currency units");
.man.registerArg (".qrisk.carry_pnl";"param";"fwd";"outright forward rate");
.man.registerArg (".qrisk.carry_pnl";"param";"spot";"spot rate");
.man.registerArg (".qrisk.carry_pnl";"eg";"";".qrisk.carry_pnl[1000000;1.10;1.1050]  -> 5000f");
.man.registerArg (".qrisk.carry_pnl";"return";"";"the carry P&L, in quote currency");
.man.registerFunc (".qrisk.carry_return";".qrisk";"Forward premium/discount implied by spot vs. an outright, as a decimal return: (F-S)/S. Positive means the base currency trades forward at a premium (i.e. rf is below rd under CIRP).";".qrisk.carry_return";".qrisk.carry_return[1.10;1.1050]  -> 0.004545455");
.man.registerArg (".qrisk.carry_return";"param";"fwd";"outright forward rate");
.man.registerArg (".qrisk.carry_return";"param";"spot";"spot rate");
.man.registerArg (".qrisk.carry_return";"eg";"";".qrisk.carry_return[1.10;1.1050]  -> 0.004545455");
.man.registerArg (".qrisk.carry_return";"return";"";"the decimal forward premium/discount");
.man.registerFunc (".qrisk.pip_value";".qrisk";"Money value of a 1-pip move on a given base-currency notional, in quote currency.";".qrisk.pip_value";".qrisk.pip_value[1000000;10000]  -> 100f");
.man.registerArg (".qrisk.pip_value";"param";"notional";"position size in base currency units");
.man.registerArg (".qrisk.pip_value";"param";"pip_factor";"10000 for most pairs, 100 for JPY crosses");
.man.registerArg (".qrisk.pip_value";"eg";"";".qrisk.pip_value[1000000;10000]  -> 100f");
.man.registerArg (".qrisk.pip_value";"return";"";"the value of a 1-pip move, in quote currency");
.man.registerFunc (".qrisk.pnl";".qrisk";"Mark-to-market P&L of a spot position, in quote currency.";".qrisk.pnl";".qrisk.pnl[1000000;1.1000;1.1050;1]  -> 5000f");
.man.registerArg (".qrisk.pnl";"param";"notional";"position size in base currency units");
.man.registerArg (".qrisk.pnl";"param";"side";"1 for long base currency, -1 for short");
.man.registerArg (".qrisk.pnl";"param";"entry_rate";"the rate the position was opened at");
.man.registerArg (".qrisk.pnl";"param";"exit_rate";"the current/closing rate");
.man.registerArg (".qrisk.pnl";"eg";"";".qrisk.pnl[1000000;1.1000;1.1050;1]  -> 5000f");
.man.registerArg (".qrisk.pnl";"return";"";"the P&L, in quote currency");
.man.registerFunc (".qrisk.var_historical";".qrisk";"Historical simulation VaR: the magnitude of the (1-confidence) empirical percentile of a series of historical P&L outcomes.";".qrisk.var_historical";".qrisk.var_historical[-100+til 200;0.95]  -> 90 (5th percentile of a 200-outcome series)");
.man.registerArg (".qrisk.var_historical";"param";"pnl_series";"a list of historical P&L outcomes");
.man.registerArg (".qrisk.var_historical";"param";"confidence";"one-tailed confidence level, e.g. 0.95 or 0.99");
.man.registerArg (".qrisk.var_historical";"eg";"";".qrisk.var_historical[-100+til 200;0.95]  -> 90 (5th percentile of a 200-outcome series)");
.man.registerArg (".qrisk.var_historical";"return";"";"a positive loss estimate, in the same units as pnl_series");
.man.registerFunc (".qrisk.var_parametric";".qrisk";"One-sided parametric (variance-covariance) VaR for a position with annualised volatility vol over a horizon of t years, at a one-tailed confidence level (e.g. 0.95, 0.99).";".qrisk.var_parametric";".qrisk.var_parametric[1000000;0.10;1%252;0.95]  -> 10361.6 (1-day 95% VaR)");
.man.registerArg (".qrisk.var_parametric";"param";"notional";"position size (sign ignored - VaR is a loss magnitude)");
.man.registerArg (".qrisk.var_parametric";"param";"vol";"annualised volatility, decimal (0.10 = 10%)");
.man.registerArg (".qrisk.var_parametric";"param";"t";"horizon, year fraction (e.g. 1%252 for one trading day)");
.man.registerArg (".qrisk.var_parametric";"param";"confidence";"one-tailed confidence level, e.g. 0.95 or 0.99");
.man.registerArg (".qrisk.var_parametric";"eg";"";".qrisk.var_parametric[1000000;0.10;1%252;0.95]  -> 10361.6 (1-day 95% VaR)");
.man.registerArg (".qrisk.var_parametric";"return";"";"a positive loss estimate, in the notional's currency");
.man.registerFile ("data.q";"";".qdata";"data.q - optional Databento parquet data access, keyed by symbol and date. Not loaded by src/init.q: it needs a real kdb+/KDB-X interpreter (PeachQ has no `2:`, so it can't load KX's native pq module) and a local .env pointing at the data. Load explicitly with `\l src/data.q`.  Expects DATABENTO_DATA_DIR (from a repo-root .env file, or the OS environment) to point at a folder laid out as: <DATABENTO_DATA_DIR>/<SYMBOL>/<SYMBOL>_<YYYY-MM-DD>_raw_mbp-10_us_hours.parquet .");
.man.registerFunc (".qdata.cfg";".qdata";"Look up a config value: the OS environment first, then the parsed .env dict, then the given default.";".qdata.cfg";".qdata.cfg[`DATABENTO_DATA_DIR;::]");
.man.registerArg (".qdata.cfg";"param";"dflt";"fallback value, or generic null (::) to error if unset");
.man.registerArg (".qdata.cfg";"param";"k";"the variable name, e.g. `DATABENTO_DATA_DIR`");
.man.registerArg (".qdata.cfg";"eg";"";".qdata.cfg[`DATABENTO_DATA_DIR;::]");
.man.registerArg (".qdata.cfg";"throws";"";"configMissing if k isn't set anywhere and no default was given");
.man.registerArg (".qdata.cfg";"return";"";"the string value");
.man.registerFunc (".qdata.databentoDir";".qdata";"Root folder for locally-available Databento parquet dumps (DATABENTO_DATA_DIR), one subfolder per symbol.";".qdata.databentoDir";".qdata.databentoDir[]");
.man.registerArg (".qdata.databentoDir";"eg";"";".qdata.databentoDir[]");
.man.registerArg (".qdata.databentoDir";"throws";"";"configMissing if DATABENTO_DATA_DIR isn't set anywhere");
.man.registerArg (".qdata.databentoDir";"return";"";"the configured folder path, as a string");
.man.registerFunc (".qdata.databentoFile";".qdata";"Expected path to one symbol/date's daily Databento MBP-10 parquet file.";".qdata.databentoFile";".qdata.databentoFile[`AAPL;2026.02.25]");
.man.registerArg (".qdata.databentoFile";"param";"date";"a q date, e.g. 2026.02.25");
.man.registerArg (".qdata.databentoFile";"param";"sym";"ticker symbol, e.g. `AAPL`");
.man.registerArg (".qdata.databentoFile";"eg";"";".qdata.databentoFile[`AAPL;2026.02.25]");
.man.registerArg (".qdata.databentoFile";"return";"";"an hsym (file symbol) - the file need not exist yet");
.man.registerFunc (".qdata.env";".qdata";"Parsed contents of the repo-root .env file, if present - see parseEnv.";".qdata.env";"");
.man.registerFunc (".qdata.getBySymbolDate";".qdata";"Open one symbol/date's Databento parquet file as a lazy, row-group-pruned virtual table (via pqModule) - select from it like a normal table, e.g. select avg price by 1 xbar ts_event.minute from .qdata.getBySymbolDate[`AAPL;2026.02.25]";".qdata.getBySymbolDate";".qdata.getBySymbolDate[`AAPL;2026.02.25]");
.man.registerArg (".qdata.getBySymbolDate";"param";"date";"a q date, e.g. 2026.02.25");
.man.registerArg (".qdata.getBySymbolDate";"param";"sym";"ticker symbol, e.g. `AAPL`");
.man.registerArg (".qdata.getBySymbolDate";"eg";"";".qdata.getBySymbolDate[`AAPL;2026.02.25]");
.man.registerArg (".qdata.getBySymbolDate";"throws";"";"fileNotFound if no file exists for that symbol/date");
.man.registerArg (".qdata.getBySymbolDate";"return";"";"a virtual table handle over the matching parquet file");
.man.registerFunc (".qdata.parseEnv";".qdata";"Parse a .env-style file (KEY=VALUE lines; blank lines and lines starting with `#` are ignored) into a dict. Missing file -> empty dict, so this is safe to call unconditionally at load time.";".qdata.parseEnv";".qdata.parseEnv[`:.env]");
.man.registerArg (".qdata.parseEnv";"param";"file";"the .env file to parse, e.g. `:.env`");
.man.registerArg (".qdata.parseEnv";"eg";"";".qdata.parseEnv[`:.env]");
.man.registerArg (".qdata.parseEnv";"return";"";"a symbol!string dict of the parsed key/value pairs");
.man.registerFunc (".qdata.pqModule";".qdata";"";".qdata.pqModule";"");
.man.registerFunc (".qdata.pqm";".qdata";"KX's official pq module (github kx.com KDB-X distribution), loaded and memoized on first use rather than at file-load time, so simply loading data.q doesn't require a module-capable interpreter.";".qdata.pqm";".qdata.pqModule[][`pq]");
.man.registerArg (".qdata.pqm";"eg";"";".qdata.pqModule[][`pq]");
.man.registerArg (".qdata.pqm";"throws";"";"if `use` (KDB-X's module loader) is unavailable - real kdb+/KDB-X is required here, not PeachQ");
.man.registerArg (".qdata.pqm";"return";"";"the pq module namespace, exposing `.pq` (open file), `.op`/`.rd` (low-level access)");
.man.registerFile ("daycount.q";"";".qdcf";"daycount.q - day count fraction conventions used to turn a pair of dates into the year fraction t consumed by rates.q / forwards.q / options.q. . NOTE ON q ARITHMETIC: q has no operator precedence (strictly right to left evaluation), so every mixed +/-/* expression below is built from explicitly parenthesised, named intermediate terms rather than dense one-liners - see src/stats.q for the bug this avoids.");
.man.registerFunc (".qdcf.dcf_30e_360";".qdcf";"30E/360 (Eurobond basis): each month treated as having 30 days. Day-of-month is capped at 30 for both dates (the simple European variant - it does not carry the US/NASD end-of-February special case).";".qdcf.dcf_30e_360";".qdcf.dcf_30e_360[2024.01.15;2024.02.15]  -> 0.08333333 (30/360)");
.man.registerArg (".qdcf.dcf_30e_360";"param";"d1";"start date");
.man.registerArg (".qdcf.dcf_30e_360";"param";"d2";"end date");
.man.registerArg (".qdcf.dcf_30e_360";"eg";"";".qdcf.dcf_30e_360[2024.01.15;2024.02.15]  -> 0.08333333 (30/360)");
.man.registerArg (".qdcf.dcf_30e_360";"return";"";"the 30E/360 year fraction between d1 and d2");
.man.registerFunc (".qdcf.dcf_act_360";".qdcf";"Actual/360: (d2-d1) actual calendar days, annualised on a 360-day year. Common for USD, EUR money-market and most FX deposit/forward calcs.";".qdcf.dcf_act_360";".qdcf.dcf_act_360[2024.01.01;2025.01.01]  -> 1.016667 (2024 is a leap year)");
.man.registerArg (".qdcf.dcf_act_360";"param";"d1";"start date");
.man.registerArg (".qdcf.dcf_act_360";"param";"d2";"end date");
.man.registerArg (".qdcf.dcf_act_360";"eg";"";".qdcf.dcf_act_360[2024.01.01;2025.01.01]  -> 1.016667 (2024 is a leap year)");
.man.registerArg (".qdcf.dcf_act_360";"return";"";"(d2-d1) actual days, divided by 360");
.man.registerFunc (".qdcf.dcf_act_365";".qdcf";"Actual/365 (Fixed): (d2-d1) actual calendar days, annualised on a 365-day year. Common for GBP money markets.";".qdcf.dcf_act_365";".qdcf.dcf_act_365[2023.01.01;2024.01.01]  -> 1f");
.man.registerArg (".qdcf.dcf_act_365";"param";"d1";"start date");
.man.registerArg (".qdcf.dcf_act_365";"param";"d2";"end date");
.man.registerArg (".qdcf.dcf_act_365";"eg";"";".qdcf.dcf_act_365[2023.01.01;2024.01.01]  -> 1f");
.man.registerArg (".qdcf.dcf_act_365";"return";"";"(d2-d1) actual days, divided by 365");
.man.registerFunc (".qdcf.year_frac";".qdcf";"Dispatch to a day count convention by name.";".qdcf.year_frac";".qdcf.year_frac[`act360;2024.01.01;2025.01.01]  -> 1.016667");
.man.registerArg (".qdcf.year_frac";"param";"conv";"one of `act360`act365`30e360");
.man.registerArg (".qdcf.year_frac";"param";"d1";"start date");
.man.registerArg (".qdcf.year_frac";"param";"d2";"end date");
.man.registerArg (".qdcf.year_frac";"eg";"";".qdcf.year_frac[`act360;2024.01.01;2025.01.01]  -> 1.016667");
.man.registerArg (".qdcf.year_frac";"throws";"";"error if conv is not one of the supported symbols");
.man.registerArg (".qdcf.year_frac";"return";"";"the year fraction between d1 and d2 under the chosen convention");
.man.registerFile ("stats.q";"";".qstats";"stats.q - normal distribution helpers used throughout uqf. ncdf/npdf use the Abramowitz & Stegun 7.1.26 rational approximation to the error function (max absolute error ~1.5e-7). inv_ncdf uses Peter Acklam's rational approximation to the inverse standard normal CDF (max relative error ~1.15e-9), released by its author into the public domain. See: https://web.archive.org/web/20151030215612/http://home.online.no/~pjacklam/notes/invnorm/ .");
.man.registerFunc (".qstats.PI";".qstats";"The constant pi, used by npdf.";".qstats.PI";"");
.man.registerFunc (".qstats.horner_eval";".qstats";"Evaluate a polynomial at x via Horner's method - the one place q's lack of operator precedence for hand-written Horner chains is worked out and tested, so no other formula in this repo has to re-derive it. See the kdb-q-conventions skill for why (`a*x+b` means `a*(x+b)` in q, not `(a*x)+b`, which silently broke early drafts of this function).";".qstats.horner_eval";".qstats.horner_eval[2 3 4;5]  -> 69 (i.e. 2*5*5+3*5+4)");
.man.registerArg (".qstats.horner_eval";"param";"coeffs";"polynomial coefficients, highest degree first, constant term last (as in numpy.polyval)");
.man.registerArg (".qstats.horner_eval";"param";"x";"the point to evaluate the polynomial at");
.man.registerArg (".qstats.horner_eval";"eg";"";".qstats.horner_eval[2 3 4;5]  -> 69 (i.e. 2*5*5+3*5+4)");
.man.registerArg (".qstats.horner_eval";"return";"";"coeffs[0]*x^n + coeffs[1]*x^(n-1) + ... + coeffs[n]");
.man.registerFunc (".qstats.inv_ncdf";".qstats";"Inverse standard normal CDF (probit function).";".qstats.inv_ncdf";".qstats.inv_ncdf 0.95  -> 1.644854 (the one-tailed 95% z-score)");
.man.registerArg (".qstats.inv_ncdf";"param";"p";"probability, strictly within (0,1); an atom or a list of atoms");
.man.registerArg (".qstats.inv_ncdf";"eg";"";".qstats.inv_ncdf 0.95  -> 1.644854 (the one-tailed 95% z-score)");
.man.registerArg (".qstats.inv_ncdf";"throws";"";"error if any element of p is not strictly between 0 and 1");
.man.registerArg (".qstats.inv_ncdf";"return";"";"x such that ncdf[x]~p");
.man.registerFunc (".qstats.ncdf";".qstats";"Standard normal cumulative distribution function N(x).";".qstats.ncdf";".qstats.ncdf 1.96  -> 0.9750022");
.man.registerArg (".qstats.ncdf";"param";"x";"point(s) to evaluate at (atom or vector)");
.man.registerArg (".qstats.ncdf";"eg";"";".qstats.ncdf 1.96  -> 0.9750022");
.man.registerArg (".qstats.ncdf";"return";"";"P(Z is at most x) for a standard normal Z");
.man.registerFunc (".qstats.npdf";".qstats";"Standard normal probability density function n(x).";".qstats.npdf";".qstats.npdf 0f  -> 0.3989423");
.man.registerArg (".qstats.npdf";"param";"x";"point(s) to evaluate at (atom or vector)");
.man.registerArg (".qstats.npdf";"eg";"";".qstats.npdf 0f  -> 0.3989423");
.man.registerArg (".qstats.npdf";"return";"";"the standard normal density at x");
.man.registerFile ("forwards.q";"";".qfwd";"forwards.q - FX forward/swap points via covered interest rate parity (CIRP), and rate/cross-rate helpers used on an eFX forwards desk. . Currency pair convention: a rate quoted BASE/QUOTE means 1 unit of BASE buys `rate` units of QUOTE (e.g. EURUSD 1.1000 -> 1 EUR = 1.10 USD). rd is the QUOTE currency's interest rate, rf the BASE currency's.");
.man.registerFunc (".qfwd.book_crossed";".qfwd";"True if a book is crossed (bid > ask) - a sanity check for synthetic books built from cross_book/combine_oriented_books.";".qfwd.book_crossed";".qfwd.book_crossed[`bid`ask!(1.1000;1.1002)]  -> 0b");
.man.registerArg (".qfwd.book_crossed";"param";"book";"a dict `bid`ask!(bidPx;askPx)");
.man.registerArg (".qfwd.book_crossed";"eg";"";".qfwd.book_crossed[`bid`ask!(1.1000;1.1002)]  -> 0b");
.man.registerArg (".qfwd.book_crossed";"return";"";"1b if bid>ask, else 0b");
.man.registerFunc (".qfwd.ccy_orient_cross";".qfwd";"Private: work out how two currency pairs relate - which currency they share, what the resulting cross pair's symbol is, and whether either leg needs inverting before combining - without touching any prices. Shared by cross_book and cross_book_at_sizes so the two can never disagree about orientation.";".qfwd.ccy_orient_cross";".qfwd.ccy_orient_cross[`EURUSD;`USDJPY]  -> `cross_sym`invert1`invert2!(`EURJPY;0b;0b)");
.man.registerArg (".qfwd.ccy_orient_cross";"param";"sym1";"currency pair for leg 1, any format ccy.q's normalize_ccy_pair accepts");
.man.registerArg (".qfwd.ccy_orient_cross";"param";"sym2";"currency pair for leg 2, any format ccy.q's normalize_ccy_pair accepts");
.man.registerArg (".qfwd.ccy_orient_cross";"eg";"";".qfwd.ccy_orient_cross[`EURUSD;`USDJPY]  -> `cross_sym`invert1`invert2!(`EURJPY;0b;0b)");
.man.registerArg (".qfwd.ccy_orient_cross";"throws";"";"error if sym1 and sym2 share no common currency");
.man.registerArg (".qfwd.ccy_orient_cross";"return";"";"dict `cross_sym`invert1`invert2 - cross_sym is the resulting pair symbol; invert1/invert2 say whether that leg's quote convention needs flipping (BASE/QUOTE -> QUOTE/BASE) before combining");
.man.registerFunc (".qfwd.combine_oriented_books";".qfwd";"Combine two order books that are already oriented A/B and B/C (i.e. the quote currency of the first leg matches the base currency of the second) into a top-of-book A/C book. Private building block for cross_book; call directly if you've already oriented the legs yourself.";".qfwd.combine_oriented_books";".qfwd.combine_oriented_books[`bid`ask!(1.1000;1.1002);`bid`ask!(150.00;150.02)]  -> `bid`ask!(165;165.052)");
.man.registerArg (".qfwd.combine_oriented_books";"param";"book_ab";"dict `bid`ask!(bidPx;askPx) quoted A/B");
.man.registerArg (".qfwd.combine_oriented_books";"param";"book_bc";"dict `bid`ask!(bidPx;askPx) quoted B/C");
.man.registerArg (".qfwd.combine_oriented_books";"eg";"";".qfwd.combine_oriented_books[`bid`ask!(1.1000;1.1002);`bid`ask!(150.00;150.02)]  -> `bid`ask!(165;165.052)");
.man.registerArg (".qfwd.combine_oriented_books";"return";"";"dict `bid`ask!(bidPx;askPx) quoted A/C");
.man.registerFunc (".qfwd.cross_book";".qfwd";"Build a synthetic top-of-book cross rate from two live order books on pairs that share a common currency, e.g. cross_book[`EURUSD;eurusd_book; `USDJPY;usdjpy_book] -> a synthetic EURJPY book. The shared currency is detected automatically and either leg is inverted as needed - the caller does not need to pre-orient anything. sym1/sym2 are normalized via ccy.q's ccy_pair_legs, so `eurusd, \"eur/usd\" etc. work too, not just canonical `EURUSD. Combines top-of-book only; it does not walk/net multiple depth levels of the underlying books - see cross_book_at_sizes for that.";".qfwd.cross_book";".qfwd.cross_book[`EURUSD;`bid`ask!(1.1000;1.1002);`USDJPY;`bid`ask!(150.00;150.02)]  -> `sym`bid`ask!(`EURJPY;165;165.052)");
.man.registerArg (".qfwd.cross_book";"param";"book2";"dict `bid`ask!(bidPx;askPx) quoted in sym2's own convention");
.man.registerArg (".qfwd.cross_book";"param";"book1";"dict `bid`ask!(bidPx;askPx) quoted in sym1's own convention");
.man.registerArg (".qfwd.cross_book";"param";"sym1";"currency pair for book1, any format ccy.q's normalize_ccy_pair accepts");
.man.registerArg (".qfwd.cross_book";"param";"sym2";"currency pair for book2, any format ccy.q's normalize_ccy_pair accepts");
.man.registerArg (".qfwd.cross_book";"eg";"";".qfwd.cross_book[`EURUSD;`bid`ask!(1.1000;1.1002);`USDJPY;`bid`ask!(150.00;150.02)]  -> `sym`bid`ask!(`EURJPY;165;165.052)");
.man.registerArg (".qfwd.cross_book";"throws";"";"error if sym1 and sym2 share no common currency");
.man.registerArg (".qfwd.cross_book";"return";"";"dict `sym`bid`ask!(cross_sym;bidPx;askPx) for the synthetic cross");
.man.registerFunc (".qfwd.cross_book_at_one_size";".qfwd";"Private: bid, ask and mid for a 2-leg cross at a single size. mid is the average of the swept cross bid and the swept cross ask at that size (not a separate sweep of its own).";".qfwd.cross_book_at_one_size";"");
.man.registerArg (".qfwd.cross_book_at_one_size";"param";"book2";"dict `bid_prices`bid_sizes`ask_prices`ask_sizes for leg 2");
.man.registerArg (".qfwd.cross_book_at_one_size";"param";"book1";"dict `bid_prices`bid_sizes`ask_prices`ask_sizes for leg 1");
.man.registerArg (".qfwd.cross_book_at_one_size";"param";"size";"the size to sweep, in leg 1's relevant currency");
.man.registerArg (".qfwd.cross_book_at_one_size";"param";"sym1";"currency pair for leg 1");
.man.registerArg (".qfwd.cross_book_at_one_size";"param";"sym2";"currency pair for leg 2");
.man.registerArg (".qfwd.cross_book_at_one_size";"return";"";"one row: dict `size`sym`bid`bid_filled_size`bid_fully_filled`ask`ask_filled_size`ask_fully_filled`mid");
.man.registerFunc (".qfwd.cross_book_at_sizes";".qfwd";"Depth-aware synthetic cross rate: like cross_book, but walks multi-level order book depth on both legs for each requested size, converting the notional hop-by-hop (leg 2 is swept at the bridge-currency amount leg 1's sweep actually produced), and returns only the sides you ask for. Each leg's book must supply real depth, not just top-of-book - see sweep_price's book shape.";".qfwd.cross_book_at_sizes";".qfwd.cross_book_at_sizes[`EURUSD;eurusd_book;`USDJPY;usdjpy_book;1000000 3000000;`bid`ask`mid]");
.man.registerArg (".qfwd.cross_book_at_sizes";"param";"book2";"dict `bid_prices`bid_sizes`ask_prices`ask_sizes for leg 2, each level best-first");
.man.registerArg (".qfwd.cross_book_at_sizes";"param";"book1";"dict `bid_prices`bid_sizes`ask_prices`ask_sizes for leg 1, each level best-first");
.man.registerArg (".qfwd.cross_book_at_sizes";"param";"sizes";"list of sizes to price, e.g. 1000000 2000000 5000000");
.man.registerArg (".qfwd.cross_book_at_sizes";"param";"sides";"subset of `bid`ask`mid to include in the result");
.man.registerArg (".qfwd.cross_book_at_sizes";"param";"sym1";"currency pair for leg 1, any format ccy.q's normalize_ccy_pair accepts");
.man.registerArg (".qfwd.cross_book_at_sizes";"param";"sym2";"currency pair for leg 2, any format ccy.q's normalize_ccy_pair accepts");
.man.registerArg (".qfwd.cross_book_at_sizes";"eg";"";".qfwd.cross_book_at_sizes[`EURUSD;eurusd_book;`USDJPY;usdjpy_book;1000000 3000000;`bid`ask`mid]");
.man.registerArg (".qfwd.cross_book_at_sizes";"throws";"";"error if sym1 and sym2 share no common currency, or sides has anything other than `bid`ask`mid");
.man.registerArg (".qfwd.cross_book_at_sizes";"return";"";"a table, one row per size, columns `size`sym plus whichever of bid/bid_filled_size/bid_fully_filled, ask/ask_filled_size/ask_fully_filled, mid were requested via sides");
.man.registerFunc (".qfwd.cross_rate";".qfwd";"Triangulate a cross rate: A/B * B/C = A/C.";".qfwd.cross_rate";".qfwd.cross_rate[1.10;150]  -> 165f (EURUSD * USDJPY -> EURJPY)");
.man.registerArg (".qfwd.cross_rate";"param";"ab_rate";"rate for A/B");
.man.registerArg (".qfwd.cross_rate";"param";"bc_rate";"rate for B/C");
.man.registerArg (".qfwd.cross_rate";"eg";"";".qfwd.cross_rate[1.10;150]  -> 165f (EURUSD * USDJPY -> EURJPY)");
.man.registerArg (".qfwd.cross_rate";"return";"";"the implied rate for A/C");
.man.registerFunc (".qfwd.cross_rate_shared_base";".qfwd";"Cross rate via a shared base currency: given two pairs both quoted A/X and A/Y (e.g. EURPLN and EURUSD both quoted against EUR), returns the Y/X cross rate - the common eFX pattern of computing e.g. USDPLN from EURPLN and EURUSD as EURPLN * (1/EURUSD). Simply cross_rate composed with invert_rate; kept as its own named function because \"invert the second one, not the first\" is exactly the kind of thing that's easy to get backwards at the desk.";".qfwd.cross_rate_shared_base";".qfwd.cross_rate_shared_base[4.30;1.075]  -> 4f (EURPLN, EURUSD -> USDPLN)");
.man.registerArg (".qfwd.cross_rate_shared_base";"param";"rate_ax";"rate for A/X (the shared base A over the first quote currency X)");
.man.registerArg (".qfwd.cross_rate_shared_base";"param";"rate_ay";"rate for A/Y (the shared base A over the second quote currency Y)");
.man.registerArg (".qfwd.cross_rate_shared_base";"eg";"";".qfwd.cross_rate_shared_base[4.30;1.075]  -> 4f (EURPLN, EURUSD -> USDPLN)");
.man.registerArg (".qfwd.cross_rate_shared_base";"return";"";"the implied rate for Y/X");
.man.registerFunc (".qfwd.cross_sweep_side";".qfwd";"Private: sweep one side of a 2-leg cross at one size, converting the notional hop-by-hop - leg 2 is swept at the amount of the shared/bridge currency that leg 1's sweep actually produced, not at the raw input size.";".qfwd.cross_sweep_side";"");
.man.registerArg (".qfwd.cross_sweep_side";"param";"book2";"dict `bid_prices`bid_sizes`ask_prices`ask_sizes for leg 2");
.man.registerArg (".qfwd.cross_sweep_side";"param";"book1";"dict `bid_prices`bid_sizes`ask_prices`ask_sizes for leg 1");
.man.registerArg (".qfwd.cross_sweep_side";"param";"side";"`bid or `ask - the side of the final cross being priced");
.man.registerArg (".qfwd.cross_sweep_side";"param";"size";"the size to sweep, in leg 1's relevant currency");
.man.registerArg (".qfwd.cross_sweep_side";"param";"invert1";"1b if leg 1 needs its convention flipped");
.man.registerArg (".qfwd.cross_sweep_side";"param";"invert2";"1b if leg 2 needs its convention flipped");
.man.registerArg (".qfwd.cross_sweep_side";"return";"";"dict `price`filled_size`fully_filled for this side of the cross");
.man.registerFunc (".qfwd.fwd_cont";".qfwd";"Outright forward rate under continuous-compounding CIRP: F = S*exp((rd-rf)*t)";".qfwd.fwd_cont";".qfwd.fwd_cont[1.10;0.05;0.02;1]  -> 1.1335");
.man.registerArg (".qfwd.fwd_cont";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qfwd.fwd_cont";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qfwd.fwd_cont";"param";"t";"year fraction to the forward date");
.man.registerArg (".qfwd.fwd_cont";"param";"spot";"spot rate, BASE/QUOTE");
.man.registerArg (".qfwd.fwd_cont";"eg";"";".qfwd.fwd_cont[1.10;0.05;0.02;1]  -> 1.1335");
.man.registerArg (".qfwd.fwd_cont";"return";"";"the outright forward rate");
.man.registerFunc (".qfwd.fwd_points";".qfwd";"Forward points = (F-S) scaled into pips.";".qfwd.fwd_points";".qfwd.fwd_points[1.132353;1.10;10000]  -> 323.53");
.man.registerArg (".qfwd.fwd_points";"param";"fwd";"outright forward rate");
.man.registerArg (".qfwd.fwd_points";"param";"spot";"spot rate");
.man.registerArg (".qfwd.fwd_points";"param";"pip_factor";"10000 for most pairs, 100 for JPY crosses");
.man.registerArg (".qfwd.fwd_points";"eg";"";".qfwd.fwd_points[1.132353;1.10;10000]  -> 323.53");
.man.registerArg (".qfwd.fwd_points";"return";"";"the forward points, in pips");
.man.registerFunc (".qfwd.fwd_simple";".qfwd";"Outright forward rate under simple-interest CIRP: F = S*(1+rd*t)/(1+rf*t)";".qfwd.fwd_simple";".qfwd.fwd_simple[1.10;0.05;0.02;1]  -> 1.132353");
.man.registerArg (".qfwd.fwd_simple";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qfwd.fwd_simple";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qfwd.fwd_simple";"param";"t";"year fraction to the forward date");
.man.registerArg (".qfwd.fwd_simple";"param";"spot";"spot rate, BASE/QUOTE");
.man.registerArg (".qfwd.fwd_simple";"eg";"";".qfwd.fwd_simple[1.10;0.05;0.02;1]  -> 1.132353");
.man.registerArg (".qfwd.fwd_simple";"return";"";"the outright forward rate");
.man.registerFunc (".qfwd.implied_domestic_rate";".qfwd";"Back out the implied domestic (quote currency) rate from an observed outright, given the foreign (base currency) rate - simple CIRP inverse.";".qfwd.implied_domestic_rate";".qfwd.implied_domestic_rate[1.10;1.132353;0.02;1]  -> 0.05");
.man.registerArg (".qfwd.implied_domestic_rate";"param";"fwd";"observed outright forward rate");
.man.registerArg (".qfwd.implied_domestic_rate";"param";"rf";"foreign (base currency) decimal annual rate");
.man.registerArg (".qfwd.implied_domestic_rate";"param";"t";"year fraction to the forward date");
.man.registerArg (".qfwd.implied_domestic_rate";"param";"spot";"spot rate");
.man.registerArg (".qfwd.implied_domestic_rate";"eg";"";".qfwd.implied_domestic_rate[1.10;1.132353;0.02;1]  -> 0.05");
.man.registerArg (".qfwd.implied_domestic_rate";"return";"";"the implied domestic (quote currency) decimal annual rate");
.man.registerFunc (".qfwd.implied_foreign_rate";".qfwd";"Back out the implied foreign (base currency) rate from an observed outright, given the domestic (quote currency) rate - simple CIRP inverse.";".qfwd.implied_foreign_rate";".qfwd.implied_foreign_rate[1.10;1.132353;0.05;1]  -> 0.02");
.man.registerArg (".qfwd.implied_foreign_rate";"param";"fwd";"observed outright forward rate");
.man.registerArg (".qfwd.implied_foreign_rate";"param";"rd";"domestic (quote currency) decimal annual rate");
.man.registerArg (".qfwd.implied_foreign_rate";"param";"t";"year fraction to the forward date");
.man.registerArg (".qfwd.implied_foreign_rate";"param";"spot";"spot rate");
.man.registerArg (".qfwd.implied_foreign_rate";"eg";"";".qfwd.implied_foreign_rate[1.10;1.132353;0.05;1]  -> 0.02");
.man.registerArg (".qfwd.implied_foreign_rate";"return";"";"the implied foreign (base currency) decimal annual rate");
.man.registerFunc (".qfwd.invert_book";".qfwd";"Invert an order book: BASE/QUOTE -> QUOTE/BASE. Inverting flips which side is more favourable, so the new bid comes from the old ask and vice versa.";".qfwd.invert_book";".qfwd.invert_book[`bid`ask!(1.1000;1.1002)]  -> `bid`ask!(0.9089256;0.9090909)");
.man.registerArg (".qfwd.invert_book";"param";"book";"a dict `bid`ask!(bidPx;askPx) quoted BASE/QUOTE");
.man.registerArg (".qfwd.invert_book";"eg";"";".qfwd.invert_book[`bid`ask!(1.1000;1.1002)]  -> `bid`ask!(0.9089256;0.9090909)");
.man.registerArg (".qfwd.invert_book";"return";"";"the same book quoted QUOTE/BASE");
.man.registerFunc (".qfwd.invert_book_depth";".qfwd";"Invert a multi-level depth ladder: BASE/QUOTE -> QUOTE/BASE. Prices invert elementwise (order stays best-first automatically: inverting a monotonic ladder reverses its sense exactly the way flipping ask<->bid requires). Sizes rescale into the new base currency - a level of size BASE units at price QUOTE/BASE is worth size*price QUOTE units, which become the new base currency's size.";".qfwd.invert_book_depth";".qfwd.invert_book_depth[1.1000 1.1002;1000000 1000000]  -> (0.9090909 0.9089256;1100000 1100200)");
.man.registerArg (".qfwd.invert_book_depth";"param";"sizes";"level sizes in the ladder's own base currency, aligned to prices");
.man.registerArg (".qfwd.invert_book_depth";"param";"prices";"level prices, best-first");
.man.registerArg (".qfwd.invert_book_depth";"eg";"";".qfwd.invert_book_depth[1.1000 1.1002;1000000 1000000]  -> (0.9090909 0.9089256;1100000 1100200)");
.man.registerArg (".qfwd.invert_book_depth";"return";"";"(invertedPrices;rescaledSizes), still best-first");
.man.registerFunc (".qfwd.invert_rate";".qfwd";"Invert a quote convention: BASE/QUOTE -> QUOTE/BASE.";".qfwd.invert_rate";".qfwd.invert_rate 2f  -> 0.5");
.man.registerArg (".qfwd.invert_rate";"param";"rate";"a rate quoted BASE/QUOTE");
.man.registerArg (".qfwd.invert_rate";"eg";"";".qfwd.invert_rate 2f  -> 0.5");
.man.registerArg (".qfwd.invert_rate";"return";"";"the same rate quoted QUOTE/BASE");
.man.registerFunc (".qfwd.oriented_levels";".qfwd";"Private: the (prices;sizes) to sweep for one leg, for one side of the final cross. If this leg doesn't need inverting, that's just its own same-named side; if it does, it's the *other* original side, inverted (an inverted bid becomes an ask, and vice versa).";".qfwd.oriented_levels";"");
.man.registerArg (".qfwd.oriented_levels";"param";"side";"`bid or `ask - the side of the final cross being priced");
.man.registerArg (".qfwd.oriented_levels";"param";"invert";"1b if this leg's convention needs flipping");
.man.registerArg (".qfwd.oriented_levels";"param";"book";"dict `bid_prices`bid_sizes`ask_prices`ask_sizes for this leg");
.man.registerArg (".qfwd.oriented_levels";"return";"";"(prices;sizes) to pass to sweep_price");
.man.registerFunc (".qfwd.points_to_outright";".qfwd";"Recover the outright from spot plus forward points.";".qfwd.points_to_outright";".qfwd.points_to_outright[1.10;323.53;10000]  -> 1.132353");
.man.registerArg (".qfwd.points_to_outright";"param";"spot";"spot rate");
.man.registerArg (".qfwd.points_to_outright";"param";"pip_factor";"10000 for most pairs, 100 for JPY crosses");
.man.registerArg (".qfwd.points_to_outright";"param";"points";"forward points, in pips");
.man.registerArg (".qfwd.points_to_outright";"eg";"";".qfwd.points_to_outright[1.10;323.53;10000]  -> 1.132353");
.man.registerArg (".qfwd.points_to_outright";"return";"";"the outright forward rate");
.man.registerFunc (".qfwd.side_cols";".qfwd";"Private: the result columns contributed by one requested side.";".qfwd.side_cols";"");
