"""The process registry: one Pipeline per uqf process, DERIVED from q.

A process is declared where its code is. Every streaming job
(`.qstream.register`/`.qnorm.define` under src/etl/streaming/) and every
bounded worker (`.qbw.define` under src/etl/workers/) names the process that
runs it, the tables it reads and writes, whether it starts with the stack and
why - see model/declarations.py. This module turns those declarations into
Pipelines; model/pipelines.py derives the rows, offsets and constants.

Adding a job is adding its q file. There is no entry to write here: this was
a hand-kept tuple restating every declaration, which made each new job two
edits in two languages, and a job whose entry was forgotten a declaration no
process ran.

Two things are not read from a declaration:

* NON_JOB_PIPELINES - processes that are not a job at all (tap1 is a
  diagnostic subscriber with its own script), so there is no q to read.
* Ports. A port has to survive processes being added around it, which no
  order over files can promise, so each process's offset is remembered in
  scripts/processes/process_ports.csv - generated and append-only, like a
  lockfile. A process not yet in it is allocated the next free offset here,
  and generate_operational_docs.py writes that down.
"""

from __future__ import annotations

import csv
from dataclasses import replace
from pathlib import Path

from uqf_stack.model.declarations import Declaration, read_declarations
from uqf_stack.model.pipeline import (
    BACKFILL_RUNNER_SCRIPT,
    FROM_DECLARATION,
    STREAM_RUNNER_SCRIPT,
    Pipeline,
    PipelineKind,
)
from uqf_stack.paths import PROCESS_PORTS_FILE, TABLES_FILE, repo_root

DEFAULT_BASE_PORT = 6050

# fxfeed1 sits at the one offset the vendored process.csv leaves free below
# its own dqc/dqe block (+20..+23); every other uqf process was allocated
# contiguously from PIPELINE_BLOCK_START. Both now live in the port lock;
# these remain as the anchors a fresh lock is allocated from.
FXFEED_PINNED_OFFSET = 19
PIPELINE_BLOCK_START = 24

#: Processes that run no declared job, so nothing in q describes them.
NON_JOB_PIPELINES: tuple[Pipeline, ...] = (
    Pipeline(
        procname="tap1",
        script="processes/torq_tap.q",
        kind=PipelineKind.ETL,
        subscribes_dynamic=True,
        startwithall="0",
        note="diagnostic subscriber - started on demand, not with the whole stack",
    ),
)


def read_port_lock(root: Path) -> dict[str, int]:
    """procname -> offset, from the lock file; empty when there is none."""
    path = root / PROCESS_PORTS_FILE
    if not path.is_file():
        return {}
    rows = (line for line in path.read_text().splitlines() if not line.startswith("#"))
    return {row["procname"]: int(row["offset"]) for row in csv.DictReader(rows)}


def allocate_offsets(procnames: list[str], locked: dict[str, int]) -> dict[str, int]:
    """Every procname's offset: its locked one, or the next free after ALL
    locked offsets - retired ones included, so an offset is never reused.
    New names are allocated in sorted order, so two added at once land the
    same way on every machine."""
    offsets = {name: locked[name] for name in procnames if name in locked}
    nxt = max([PIPELINE_BLOCK_START - 1, *locked.values()]) + 1
    for name in sorted(set(procnames) - set(locked)):
        offsets[name] = nxt
        nxt += 1
    return offsets


_PORT_LOCK_HEADER = """\
# GENERATED by scripts/generate/generate_operational_docs.py - do not edit.
# Every uqf process's port, as {KDBBASEPORT}+offset. APPEND-ONLY: a process
# keeps its offset for as long as this file exists, and a retired one keeps
# its row so the offset is never handed to anything else. The processes
# themselves are read from their q declarations; this file only remembers
# where each one was put, which nothing in the tree could derive.
procname,offset
"""


def render_port_lock(locked: dict[str, int], offsets: dict[str, int]) -> str:
    """The lock file: every row it already had, plus every process it lacked,
    in offset order. Rows are never dropped - see the header it writes."""
    merged = {**offsets, **locked}
    rows = sorted(merged.items(), key=lambda item: (item[1], item[0]))
    return _PORT_LOCK_HEADER + "".join(f"{name},{offset}\n" for name, offset in rows)


def _plant_tables(root: Path) -> set[str]:
    # Imported here: schemas resolves its file at import, and this module is
    # imported by everything, so a module-scope import would fix the order.
    from uqf_stack.model.schemas import _DEFINITION

    return {m.group(1) for m in _DEFINITION.finditer((root / TABLES_FILE).read_text())}


def _owned_tables(declarations: list[Declaration], plant: set[str]) -> dict[str, str | None]:
    """procname -> the one table whose schema it owns, if exactly one.

    Ownership is what processes.md's "owns" column shows and where a
    pipeline's `schema` comes from: a table this tree defines that no other
    job publishes. A job publishing onto the vendored `quote` owns nothing;
    one sharing `config_change` still owns its own table; one with two
    tables of its own is reported as owning neither, which is how the
    registry has always described those.
    """
    publishers: dict[str, int] = {}
    for d in declarations:
        for table in d.publishes:
            publishers[table] = publishers.get(table, 0) + 1
    owned: dict[str, str | None] = {}
    for d in declarations:
        own = [t for t in d.publishes if t in plant and publishers[t] == 1]
        owned[d.procname] = own[0] if len(own) == 1 else None
    return owned


def _pipeline(d: Declaration, table: str | None, offset: int) -> Pipeline:
    if d.kind is PipelineKind.BACKFILL:
        return Pipeline(
            procname=d.procname,
            script=BACKFILL_RUNNER_SCRIPT,
            kind=d.kind,
            worker=d.name,
            startwithall="0",
            offset=offset,
            note=d.note,
        )
    return Pipeline(
        procname=d.procname,
        script=STREAM_RUNNER_SCRIPT,
        kind=d.kind,
        loads_qpipe=True,
        table=table,
        # Deferred rather than copied: the edges are resolved from the same
        # declaration by pipeline_edges, which RAISES when there is none to
        # read - the guard against a pipeline resolving to no tables (#288).
        subscribes=FROM_DECLARATION,
        publishes=FROM_DECLARATION,
        startwithall="1" if d.autostart else "0",
        offset=offset,
        note=d.note,
    )


def build_pipelines(root: Path) -> tuple[Pipeline, ...]:
    """Every uqf process, in port order."""
    declarations = read_declarations(root)
    names = [d.procname for d in declarations] + [p.procname for p in NON_JOB_PIPELINES]
    duplicates = sorted({n for n in names if names.count(n) > 1})
    if duplicates:
        raise ValueError(f"procnames claimed more than once: {duplicates}")
    offsets = allocate_offsets(names, read_port_lock(root))
    owned = _owned_tables(declarations, _plant_tables(root))
    built = [_pipeline(d, owned[d.procname], offsets[d.procname]) for d in declarations]
    built += [replace(p, offset=offsets[p.procname]) for p in NON_JOB_PIPELINES]
    return tuple(sorted(built, key=lambda p: p.offset or 0))


PIPELINES: tuple[Pipeline, ...] = build_pipelines(repo_root())
