/ declaration_load.q - which declaration files a process loads (.qetl.load, #902).
/ .
/ A declaration asks the plant for its tables AT LOAD TIME - market_data.q
/ takes `.qetl.plant.columns[`quote;...]` - so a process that loads every
/ declaration fails on the first one whose table its schema lacks, whether or
/ not it runs that job. A sidecar deployed against a managed TorQ schema
/ without `quote` could not start because the demo's market_data needed it.
/ .
/ So a process may set .qetl.load.only BEFORE loading src/etl/init.q, to the
/ procnames or job names it runs, and loads only their closure: their own
/ declarations and every source, transform, peer job and reaction those
/ reach. An empty symbol list is the infrastructure-only selection - no
/ declarations at all. Unset, the whole tree loads, as tests and the docs
/ tooling want.
/ .
/ The closure is not computed here. Resolving it in q would mean loading the
/ declarations whose failure this avoids, so python/uqs/src/uqs/model/
/ load_plan.py reads them as text and src/etl/generated/load_plan.q writes the
/ result down - .qetl.load.order, .jobs, .procs and .declares, which init.q
/ loads before this file's functions are called.

\d .qetl.load

/ The declaration files `names` select, in init.q's load order.
/ @param names procnames or job names, as a symbol list; empty selects none
/ @return the files' paths, relative to the repository root
/ @throws error naming every name the plan does not know
/ @eg .qetl.load.files `symbol$()  ->  ()
files:{[names]
    names:(),names;
    if[count bad:names where not names in key[procs],key jobs;
        '"etl load: no declared process or job named ",(", " sv string bad),
            " - src/etl/generated/load_plan.q is regenerated by",
            " scripts/generate/generate_operational_docs.py"];
    want:raze {[n] $[n in key procs; procs n; jobs n]} each names;
    order where order in want}

/ Load one declaration file, or fail naming it and the jobs it declares.
/ q's own error says what went wrong but not where, and a process that loads
/ thirty declarations cannot otherwise say which one stopped it.
/ @param f the file's path, relative to the repository root
/ @return the file's path
/ @throws error naming the file and its jobs, then q's own message
one:{[f]
    @[system;"l ",f;{[f;e]
        js:$[(`$f) in key declares; declares `$f; `symbol$()];
        '"etl load: ",f,$[count js;" (job ",(", " sv string js),")";""]," failed: ",e}[f]];
    f}

/ Load what a process selected, or every declaration when it selected none.
/ @param dirs the declaration directories, in load order, for the full load
/ @return the files loaded
declarations:{[dirs]
    fs:$[`only in key `.qetl.load; files only; raze dir_files each dirs];
    one each fs}

/ Every .q file under `dir`, alphabetically - the full load's order.
/ @param dir a directory relative to the repository root
/ @return the files' paths
/ @throws error when a required directory holds none
dir_files:{[dir]
    found:key hsym `$dir;
    found:asc found where found like "*.q";
    / Reactions may be absent or empty - a tree need have none.
    if[(0=count found) and not dir like "*reactions"; '"etl load: no .q files under ",dir];
    (dir,"/"),/:string found}

\d .
